import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  lo: {
    /* ── Nav ── */
    nav_dashboard:"Dashboard", nav_companies:"ບໍລິສັດ", nav_employees:"ພະນັກງານ",
    nav_idcard:"ບັດພະນັກງານ", nav_reports:"ລາຍງານ", nav_building:"Building",
    nav_import:"ນຳເຂົ້າຂໍ້ມູນ", nav_users:"ຜູ້ໃຊ້ລະບົບ", nav_audit:"Audit Log",
    nav_settings:"ຕັ້ງຄ່າ", nav_logout:"ອອກຈາກລະບົບ", nav_card_requests:"ຄຳຮ້ອງຂໍບັດ",
    /* ── Common ── */
    search:"ຄົ້ນຫາ", add:"ເພີ່ມ", edit:"ແກ້ໄຂ", delete:"ລຶບ", save:"ບັນທຶກ",
    cancel:"ຍົກເລີກ", confirm:"ຢືນຢັນ", reload:"ໂຫຼດໃໝ່", all:"ທັງໝົດ",
    no_data:"ບໍ່ມີຂໍ້ມູນ", loading:"ກຳລັງໂຫຼດ...", back:"ກັບຄືນ",
    export_csv:"Export CSV", print:"ພິມ", status:"ສະຖານະ", company:"ບໍລິສັດ",
    all_companies:"ທຸກບໍລິສັດ", all_status:"ທຸກສະຖານະ", name:"ຊື່",
    saving:"ກຳລັງບັນທຶກ...", save_changes:"ບັນທຶກການປ່ຽນແປງ", notes:"ໝາຍເຫດ",
    notes_placeholder:"ໝາຍເຫດ...", position:"ຕຳແໜ່ງ", gender:"ເພດ",
    nationality:"ສັນຊາດ", phone:"ເບີໂທ", send_request:"ສົ່ງຄຳຂໍ",
    page_of:"ໜ້າ {p} / {total}", showing_range:"ສະແດງ {from}–{to} ຈາກ {total} ລາຍການ",
    /* ── Reports ── */
    reports_title:"ລາຍງານ", reports_sub:"ລາຍງານຂໍ້ມູນລະບົບທັງໝົດ",
    tab_employee:"ລາຍງານພະນັກງານ", tab_building:"ລາຍງານ Building",
    select_cols:"ເລືອກຖັນ", col_code:"ລະຫັດພະນັກງານ", col_name:"ຊື່ພະນັກງານ",
    col_position:"ຕຳແໜ່ງ", col_company:"ບໍລິສັດ", col_status:"ສະຖານະ",
    col_gender:"ເພດ", col_nationality:"ສັນຊາດ", col_phone:"ເບີໂທ",
    col_passport:"ເລກ Passport", col_visa:"ເລກ Visa", deselect_all:"ຍົກເລີກ",
    select_min_col:"ກະລຸນາເລືອກຢ່າງໜ້ອຍ 1 ຖັນ", showing:"ສະແດງ", of:"ຈາກ",
    items:"ລາຍການ", total:"ທັງໝົດ", active:"Active", resigned:"Resigned",
    on_leave:"On Leave", search_emp:"ຄົ້ນຫາຊື່, ລະຫັດ, ຕຳແໜ່ງ...", no_passport:"ບໍ່ມີ",
    /* ── Building ── */
    bld_title:"Building Management", bld_sub:"ຈັດການຂໍ້ມູນ {n} ຕືກ ທັງໝົດ",
    bld_office:"Office", bld_dormitory:"ຫ້ອງນອນ", bld_floors:"ຊັ້ນ",
    bld_rooms:"ຫ້ອງ", bld_available:"ວ່າງ", bld_partial:"ຍັງວ່າງ", bld_occupied:"ມີຄົນ",
    bld_maintenance:"ສ້ອມແປງ", bld_office_bld:"ອາຄານ Office",
    bld_usage:"ການໃຊ້ງານ", bld_people:"ຄົນ", bld_floor_n:"ຊັ້ນ {n}",
    bld_lobby:"Lobby / ພື້ນທີ່ສ່ວນກາງ", bld_dorm_rooms:"ຫ້ອງນອນ ({n} ຫ້ອງ)",
    bld_avail_rooms:"ຫ້ອງວ່າງ", bld_maint_short:"ສ້ອມ", bld_total_rooms:"ທັງໝົດ {n} ຫ້ອງ",
    bld_click_change:"ກົດຫ້ອງ ເພື່ອປ່ຽນສະຖານະ",
    bld_floor_n_of_bld:"{bld} — ຊັ້ນ {n}",
    bld_office_note:"ອາຄານ Office · ທັງ {n} ຊັ້ນ",
    room_n:"ຫ້ອງ {n}", room_capacity:"ຮອງຮັບ {cap} ຄົນ · ມີ {occ} ຄົນ",
    room_full:"ຫ້ອງເຕັມແລ້ວ ({cap} ຄົນ)", room_no_occupants:"ຍັງບໍ່ມີຜູ້ພັກ",
    room_residents:"ຜູ້ພັກອາໄສ ({n})", room_status:"ສະຖານະ",
    room_add_resident:"ເພີ້ມຜູ້ພັກ", room_search:"🔍 ຄົ້ນຫາຊື່ / ລະຫັດ...",
    room_add_btn:"+ ເພີ້ມເຂົ້າຫ້ອງ", room_not_found:"ບໍ່ພົບ Employee",
    total_buildings:"ຕືກທັງໝົດ", total_rooms:"ຫ້ອງທັງໝົດ",
    available:"ຫ້ອງວ່າງ", occupied:"ຫ້ອງມີຄົນ", maintenance:"ກຳລັງສ້ອມ",
    building_name:"ຊື່ຕືກ", building_type:"ປະເພດ", floors:"ຊັ້ນ",
    search_building:"ຄົ້ນຫາຊື່ຕືກ...", all_types:"ທຸກປະເພດ", dormitory:"ຫ້ອງນອນ",
    occupancy:"ອັດຕາ%", total_occupants:"ຜູ້ພັກທັງໝົດ", buildings:"ຕືກ",
    /* ── Dashboard ── */
    male:"ຊາຍ", female:"ຍິງ", resigned_total:"ຄົນອອກ (ທັງໝົດ)",
    this_month:"ເດືອນນີ້", rooms_available:"ຫ້ອງວ່າງ (Building)",
    rooms_used:"ໃຊ້ແລ້ວ {n} ຫ້ອງ",
    /* ── Employees ── */
    employees_title:"ພະນັກງານ", add_employee:"ເພີ່ມພະນັກງານ",
    employee_code:"ລະຫັດ", employee_name:"ຊື່ພະນັກງານ",
    hire_date:"ວັນທີເຂົ້າວຽກ", manage:"ຈັດການ",
    search_emp_ph:"ຄົ້ນຫາຊື່, ລະຫັດ, ຕຳແໜ່ງ...", no_employees:"ບໍ່ພົບຂໍ້ມູນພະນັກງານ",
    clear_filter:"ລ້າງ filter", view:"ເບິ່ງ",
    found_records:"ພົບ {total} ລາຍການ (ສະແດງ {from}–{to})",
    confirm_delete_emp:"ລຶບພະນັກງານນີ້ແທ້ບໍ?",
    confirm_delete_emp_admin:"ສົ່ງຄຳຂໍລຶບພະນັກງານ?",
    delete_request_info:"ຄຳຂໍຈະຖືກສົ່ງໃຫ້ Super Admin ອະນຸຍາດກ່ອນ",
    delete_info:"ຂໍ້ມູນຈະຖືກລຶບ ແລະ ບໍ່ສາມາດກູ້ຄືນໄດ້",
    all_genders:"ທຸກເພດ",
    sort_newest:"ໃໝ່ສຸດ", sort_oldest:"ເກົ່າສຸດ",
    sort_name_az:"ຊື່ A-Z", sort_name_za:"ຊື່ Z-A",
    /* ── Companies ── */
    companies_title:"ບໍລິສັດ", company_name:"ຊື່ບໍລິສັດ",
    owner:"ເຈົ້າຂອງ", created_by:"ສ້າງໂດຍ", order_no:"ລຳດັບ",
    confirm_delete_co:"ລຶບ company ນີ້ແທ້ບໍ?",
    delete_permanent:"ຂໍ້ມູນຈະຖືກລຶບຖາວອນ ແລະ ບໍ່ສາມາດກູ້ຄືນໄດ້",
    search_owner:"ຄົ້ນຫາ owner...", no_result:"ບໍ່ພົບຜົນລັບ",
    col_in_file:"ຊື່ທີ່ພົບໃນໄຟລ໌", col_correct:"ຊື່ທີ່ຖືກຕ້ອງ",
    id_card_color_staff:"ສີ ID Card (Staff)",
    id_card_color_manager:"ສີ ID Card (ຫົວໜ້າ / Manager)",
    custom_color:"ເລືອກສີ Custom", change:"ປ່ຽນ",
    /* ── Settings ── */
    settings_title:"ຕັ້ງຄ່າ", settings_sub:"ຈັດການຂໍ້ມູນ ແລະ ການຕັ້ງຄ່າລະບົບ",
    tab_account:"ບັນຊີຜູ້ໃຊ້", tab_password:"ປ່ຽນລະຫັດຜ່ານ", tab_system:"ລະບົບ",
    account_info:"ຂໍ້ມູນບັນຊີ", account_sub:"ແກ້ໄຂຊື່ ແລະ email ຂອງທ່ານ",
    full_name:"ຊື່ເຕັມ", name_placeholder:"ຊື່ ແລະ ນາມສະກຸນ",
    current_password:"ລະຫັດຜ່ານປັດຈຸບັນ", new_password:"ລະຫັດຜ່ານໃໝ່",
    confirm_password:"ຢືນຢັນລະຫັດຜ່ານ", change_password:"ປ່ຽນລະຫັດຜ່ານ",
    password_min:"ລະຫັດຜ່ານໃໝ່ຕ້ອງຢ່າງໜ້ອຍ 6 ຕົວ",
    system_settings:"ການຕັ້ງຄ່າລະບົບ",
    system_sub:"ການຕັ້ງຄ່າທົ່ວໄປຂອງ web application",
    sys_name_label:"ຊື່ລະບົບ (ສະແດງໃນ Sidebar)",
    /* ── Admin/Users ── */
    users_title:"ຜູ້ໃຊ້ລະບົບ", users_sub:"ຈັດການ users ແລະ ສິດໃຊ້ງານລະບົບ",
    no_users:"ບໍ່ມີ users", created_at:"ສ້າງເມື່ອ",
    edit_user:"ແກ້ໄຂຂໍ້ມູນ user", create_user:"ສ້າງ user ໃໝ່ໃນລະບົບ",
    full_name_req:"ຊື່ເຕັມ *", password_req:"ລະຫັດຜ່ານ *",
    new_password_opt:"ລະຫັດຜ່ານໃໝ່ (ຍ່ອງຖ້ານ = ບໍ່ປ່ຽນ)",
    select_role:"ເລືອກ Role",
    companies_assigned:"Companies (ທີ່ assign)",
    create_company:"ສ້າງ Company ໃໝ່",
    confirm_delete_user:"ລຶບ user ນີ້ແທ້ບໍ?",
    delete_user_permanent:"ຂໍ້ມູນ user ຈະຖືກລຶບຖາວອນ",
    /* ── AuditLog ── */
    audit_title:"Audit Log", audit_sub:"ປະຫວັດການໃຊ້ງານລະບົບທັງໝົດ",
    audit_total:"ທັງໝົດ (ໜ້ານີ້)", audit_user:"ຜູ້ໃຊ້",
    audit_date:"ວັນທີ / ເວລາ", audit_no_match:"ບໍ່ມີຂໍ້ມູນທີ່ກົງກັບການຄົ້ນຫາ",
    audit_search_ph:"ຄົ້ນຫາຊື່ user, company, ປະເພດ...",
    /* ── Import ── */
    import_title:"ນຳເຂົ້າພະນັກງານ",
    import_sub:"ອັບໂຫລດໄຟລ໌ Excel ເພື່ອນຳເຂົ້າພະນັກງານ ພ້ອມ ຫ້ອງ, ເອກະສານ ແລະ ໃບອະນຸຍາດ",
    import_step1:"ຂັ້ນຕອນທີ 1: ດາວໂຫລດ Template ແລ້ວຕື່ມຂໍ້ມູນ",
    download_template:"ດາວໂຫລດ Template Excel",
    upload_file:"ອັບໂຫລດໄຟລ໌", drag_drop:"ລາກໄຟລ໌ມາວາງ ຫຼື ກົດເພື່ອເລືອກ",
    select_company:"ເລືອກ Company", upload_excel:"ອັບໂຫລດໄຟລ໌ Excel",
    reading_file:"ກຳລັງອ່ານໄຟລ໌...",
    step_upload:"ອັບໂຫລດໄຟລ໌", step_verify:"ຕຣວດສອບ Format",
    step_review:"Admin ກວດສອບ", step_done:"ສຳເລັດ",
    verify_result:"ຜົນການຕຣວດສອບ Format",
    reject_reupload:"Reject ແລະ Upload ໃໝ່",
    proceed_review:"ດຳເນີນການ → Admin ກວດສອບ ({n} ຄົນ)",
    back_review:"ກັບໄປກວດສອບ", new_upload:"ໃໝ່",
    import_success:"✅ Import ສຳເລັດ", imported:"ນຳເຂົ້າສຳເລັດ",
    skipped:"ຂ້າມ (ຊໍ້າ/ຜິດ)",
    go_employees:"ໄປໜ້າພະນັກງານ →",
    waiting_admin:"ລໍຖ້າ Super Admin ອະນຸມັດ",
    send_admin:"📤 ສົ່ງຂໍ Super Admin ອະນຸມັດ ({n} ຄົນ)",
    uploading:"ກຳລັງນຳເຂົ້າ... {n}%", sending:"ກຳລັງສົ່ງ...",
    people_to_import:"ຄົນທີ່ຈະນຳເຂົ້າ", people_skip:"ຄົນທີ່ຈະຂ້າມ (ຜິດ)",
    people_rooms:"ຄົນທີ່ມີຫ້ອງ", people_docs:"ຄົນທີ່ມີເອກະສານ",
    import_to:"ຂໍ້ມູນຈະຖືກບັນທຶກໃສ່:", import_company:"Company ທີ່ຈະນຳເຂົ້າ:",
    please_select_co:"ກະລຸນາເລືອກ Company", no_valid_rows:"ບໍ່ມີແຖວທີ່ຖືກຕ້ອງ",
    approve_import:"✅ Approve ແລະ Import {n} ຄົນ",
    upload_new:"ສົ່ງໄຟລ໌ໃໝ່", import_new:"ນຳເຂົ້າໄຟລ໌ໃໝ່",
    /* ── ID Card ── */
    idc_sub:"ຈັດການ ID Card ຂອງພະນັກງານ — ຂະໜາດ 50×85mm",
    idc_select_all:"ເລືອກທັງໝົດ", idc_print_n:"🖨 ພິມ {n} ບັດ", idc_print:"🖨 ພິມ",
    idc_select_multi:"☑ ເລືອກພິມຫຼາຍບັດ",
    idc_search_ph:"ຄົ້ນຫາຊື່, ລະຫັດ, ຕຳແໜ່ງ...",
    idc_total:"ທັງໝົດ", idc_has_card:"ມີ Card", idc_no_card:"ບໍ່ມີ Card", idc_printed:"ພິມແລ້ວ",
    idc_return_label:"ສະຖານະການຄືນບັດ — ພະນັກງານທີ່ອອກວຽກ",
    idc_has_card_resigned:"ມີບັດ (ອອກວຽກ)", idc_returned:"ຄືນແລ້ວ", idc_not_returned:"ຍັງບໍ່ທັນຄືນ",
    idc_selected_n:"☑ ເລືອກໄວ້ {n} ລາຍການ", idc_printable:"ບັດທີ່ພິມໄດ້",
    idc_no_data:"ບໍ່ມີຂໍ້ມູນ", idc_creating:"ກຳລັງສ້າງ...", idc_issue:"+ ສ້າງ Card",
    idc_card_returned_badge:"ຄືນບັດແລ້ວ", idc_saving:"ກຳລັງບັນທຶກ...", idc_receive:"📥 ຮັບຄືນບັດ",
    idc_print_card:"🖨 ພິມ Card", idc_delete_card:"ລຶບ Card",
    idc_confirm_del:"ລຶບ ID Card ນີ້ແທ້ບໍ?",
    idc_confirm_del_sub:"Card ຈະຖືກລຶບ ແລະ ພະນັກງານຈະກັບໄປ 'ບໍ່ມີ Card'",
    idc_confirm_return_sub:"ຈະບັນທຶກວ່າພະນັກງານໄດ້ຄືນ ID Card ແລ້ວ — ການກະທຳນີ້ບໍ່ສາມາດຍ້ອນຄືນໄດ້",
    idc_confirm_return_btn:"📥 ຢືນຢັນຮັບຄືນ",
    idc_prev:"← ກ່ອນ", idc_next:"ຕໍ່ໄປ →",
    idc_page_info:"ໜ້າ {p} / {total} ({n} ລາຍການ)",
    /* ── Card Requests ── */
    crq_title:"ຄຳຮ້ອງຂໍບັດ", crq_sub:"ຈັດການ ແລະ ກວດສອບຄຳຂໍອອກບັດພະນັກງານ",
    crq_new_request:"+ ສົ່ງຄຳຂໍໃໝ່",
    crq_search_ph:"ຄົ້ນຫາເລກຄຳຂໍ, ບໍລິສັດ, ຜູ້ສົ່ງ...",
    crq_pending:"ລໍຖ້າດຳເນີນ", crq_approved:"ອະນຸມັດແລ້ວ", crq_issued:"ສຳບັດແລ້ວ", crq_printed:"ພິມແລ້ວ", crq_rejected:"ປະຕິເສດ",
    crq_th_no:"ເລກຄຳຂໍ", crq_th_sender:"ຜູ້ສົ່ງຄຳຂໍ", crq_th_qty:"ຈຳນວນ", crq_th_date:"ວັນທີ",
    crq_view:"ເບິ່ງລາຍລະອຽດ", crq_download:"ດາວໂຫລດ",
    crq_employee_list:"ລາຍຊື່ພະນັກງານ", crq_acting:"ກຳລັງດຳເນີນການ...",
    crq_download_disabled_tip:"ອະນຸມັດກ່ອນຈິ່ງດາວໂຫລດໄດ້", crq_downloading:"ກຳລັງດາວໂຫລດ...",
    crq_start_review:"ເລີ່ມກວດສອບ", crq_starting_review:"ກຳລັງເປີດ...",
    crq_card_type:"ປະເພດບັດ", crq_requested_at:"ສົ່ງເມື່ອ",
    crq_no_match:"ບໍ່ມີຄຳຮ້ອງທີ່ກົງກັບການຄົ້ນຫາ",
    /* ── Card Request Detail ── */
    crq_detail_title:"ລາຍລະອຽດຄຳຮ້ອງ ID",
    crq_step_submit:"ສົ່ງຄຳຂໍ", crq_step_review:"ກວດສອບ", crq_step_approve:"ອະນຸມັດ",
    crq_step_complete:"ສຳເລັດ", crq_step_print:"ພິມບັດ", crq_step_reject:"ປະຕິເສດ",
    crq_summary_title:"ສະຫຸບຄຳຂໍ", crq_members:"ສະມາຊິກ", crq_cards:"ໃບ",
    crq_purpose:"ຈຸດປະສົງ", crq_purpose_new_card:"ອອກບັດພະນັກງານໃໝ່",
    crq_step_progress:"ຂັ້ນຕອນ {n}/5 — {label}",
    crq_pending_banner:"{name} ໄດ້ສົ່ງຄຳຂໍເຂົ້າມາແລ້ວ — ລໍຖ້າຜູ້ດູແລລະບົບກວດສອບ",
    crq_approved_banner:"ອະນຸມັດແລ້ວ — ອອກບັດ ID Card ໃຫ້ພະນັກງານທັງໝົດໃນຄຳຂໍນີ້ແລ້ວ",
    crq_rejected_banner:"ຄຳຂໍນີ້ຖືກປະຕິເສດ",
    crq_back_to_list:"← ກັບຄືນ",
    crq_step_n_of_5:"ຂັ້ນຕອນ {n}/5", crq_heading_pending:"ກຳລັງກວດສອບ",
    crq_heading_submitted:"ຄຳຂໍຖືກສົ່ງເຂົ້າມາແລ້ວ", crq_go_to_review:"ເລີ່ມກວດສອບ →",
    crq_card_summary:"ສະຫຸບປະເພດບັດ", crq_print_cards:"ສ້າງບັດ", crq_approved_ready:"ຄຳຂໍໄດ້ຮັບການອະນຸມັດແລ້ວ. ສາມາດສ້າງບັດ ID ໄດ້",
    crq_heading_issued:"ສ້າງບັດແລ້ວ — ສຳພິມ", crq_issued_banner:"ສ້າງບັດສຳເລັດ — ສາມາດເບິ່ງ ແລະ ສຳພິມໄດ້ເລີຍ",
    crq_issued_title:"ບັດທີ່ສ້າງແລ້ວ", crq_total:"ລວມ",
    crq_print_settings:"ຕັ້ງການພິມ", crq_printer_model:"ເລືອກພິມ", crq_print_quality:"ຄຸນນະພາບການພິມ",
    crq_print_name_cb:"ພິມລາຍຊື່ພະນັກງານ", crq_quick_preview:"ເບິ່ງຢ່າງດ່ວນ", crq_print_all:"ພິມບັດທັງໝົດ",
    crq_heading_complete:"ສຳເລັດສົມບູນ", crq_complete_sub:"ສຳເລັດສົມບູນ — ບັດຖືກພິມ ແລະ ເປີດໃຊ້ງານແລ້ວ",
    crq_printed_info:"ບັດ {n} ໃບ ໄດ້ຖືກພິມ · {date} · ໂດຍ {actor}",
    crq_view_id_cards:"ເບິ່ງ ID Cards", crq_back_list:"ຍ້ອນກັບ",
    crq_review_warning:"ກະລຸນາກວດສອບລາຍຊື່ ແລະ ນາມຂໍ້ມູນກ່ອນອະນຸມັດ",
    crq_admin_note_label:"ໝາຍເຫດຜູ້ດູແລ (ບໍ່ບັງຄັບ)", crq_admin_note_ph:"ໃສ່ໝາຍເຫດເພີ່ມເຕີມບ່ອນນີ້...",
    crq_approve_short:"✓ ອະນຸມັດ", crq_reject_short:"✕ ປະຕິເສດ",
    crq_rollback_to_review:"← ຍ້ອນໄປ ກວດສອບ", crq_rollback_to_approved:"← ຍ້ອນໄປ ອະນຸມັດ", crq_rollback_to_issued:"← ຍ້ອນໄປ ສ້າງບັດ",
    crq_rollback_confirm_review:"ຢືນຢັນ: ຍ້ອນກັບໄປ ກວດສອບ? ສະຖານະຈະຖືກ reset ເປັນ pending.", crq_rollback_confirm_approved:"ຢືນຢັນ: ຍ້ອນກັບໄປ ອະນຸມັດ? cards_issued ຈະຖືກ reset.", crq_rollback_confirm_issued:"ຢືນຢັນ: ຍ້ອນກັບໄປ ສ້າງບັດ? ສະຖານະພິມຈະຖືກ reset.",
  },

  en: {
    /* ── Nav ── */
    nav_dashboard:"Dashboard", nav_companies:"Companies", nav_employees:"Employees",
    nav_idcard:"ID Cards", nav_reports:"Reports", nav_building:"Building",
    nav_import:"Import Data", nav_users:"System Users", nav_audit:"Audit Log",
    nav_settings:"Settings", nav_logout:"Log Out", nav_card_requests:"Card Request",
    /* ── Common ── */
    search:"Search", add:"Add", edit:"Edit", delete:"Delete", save:"Save",
    cancel:"Cancel", confirm:"Confirm", reload:"Reload", all:"All",
    no_data:"No data found", loading:"Loading...", back:"Back",
    export_csv:"Export CSV", print:"Print", status:"Status", company:"Company",
    all_companies:"All Companies", all_status:"All Status", name:"Name",
    saving:"Saving...", save_changes:"Save Changes", notes:"Notes",
    notes_placeholder:"Notes...", position:"Position", gender:"Gender",
    nationality:"Nationality", phone:"Phone", send_request:"Send Request",
    page_of:"Page {p} / {total}", showing_range:"Showing {from}–{to} of {total} records",
    /* ── Reports ── */
    reports_title:"Reports", reports_sub:"Full system data report",
    tab_employee:"Employee Report", tab_building:"Building Report",
    select_cols:"Columns", col_code:"Employee Code", col_name:"Full Name",
    col_position:"Position", col_company:"Company", col_status:"Status",
    col_gender:"Gender", col_nationality:"Nationality", col_phone:"Phone",
    col_passport:"Passport No.", col_visa:"Visa No.", deselect_all:"Deselect",
    select_min_col:"Please select at least 1 column", showing:"Showing", of:"of",
    items:"records", total:"Total", active:"Active", resigned:"Resigned",
    on_leave:"On Leave", search_emp:"Search name, code, position...", no_passport:"None",
    /* ── Building ── */
    bld_title:"Building Management", bld_sub:"Managing {n} buildings total",
    bld_office:"Office", bld_dormitory:"Dormitory", bld_floors:"Floors",
    bld_rooms:"Rooms", bld_available:"Available", bld_partial:"Partial", bld_occupied:"Occupied",
    bld_maintenance:"Maintenance", bld_office_bld:"Office Building",
    bld_usage:"Occupancy", bld_people:"People", bld_floor_n:"Floor {n}",
    bld_lobby:"Lobby / Common Area", bld_dorm_rooms:"Dormitory ({n} rooms)",
    bld_avail_rooms:"Available rooms", bld_maint_short:"Maint.", bld_total_rooms:"Total {n} rooms",
    bld_click_change:"Click a room to change its status",
    bld_floor_n_of_bld:"{bld} — Floor {n}",
    bld_office_note:"Office Building · {n} Floors",
    room_n:"Room {n}", room_capacity:"Capacity {cap} · {occ} residents",
    room_full:"Room full ({cap} people)", room_no_occupants:"No residents yet",
    room_residents:"Residents ({n})", room_status:"Status",
    room_add_resident:"Add Resident", room_search:"🔍 Search name / code...",
    room_add_btn:"+ Add to Room", room_not_found:"Employee not found",
    total_buildings:"Total Buildings", total_rooms:"Total Rooms",
    available:"Available", occupied:"Occupied", maintenance:"Maintenance",
    building_name:"Building Name", building_type:"Type", floors:"Floors",
    search_building:"Search building name...", all_types:"All Types", dormitory:"Dormitory",
    occupancy:"Occupancy %", total_occupants:"Tenants", buildings:"buildings",
    /* ── Dashboard ── */
    male:"Male", female:"Female", resigned_total:"Resigned (Total)",
    this_month:"this month", rooms_available:"Available Rooms (Building)",
    rooms_used:"Used {n} rooms",
    /* ── Employees ── */
    employees_title:"Employees", add_employee:"Add Employee",
    employee_code:"Code", employee_name:"Full Name",
    hire_date:"Hire Date", manage:"Manage",
    search_emp_ph:"Search name, code, position...", no_employees:"No employee data found",
    clear_filter:"Clear filter", view:"View",
    found_records:"Found {total} records (showing {from}–{to})",
    confirm_delete_emp:"Delete this employee?",
    confirm_delete_emp_admin:"Send delete request?",
    delete_request_info:"Request will be sent to Super Admin for approval",
    delete_info:"Data will be deleted and cannot be recovered",
    all_genders:"All Genders",
    sort_newest:"Newest", sort_oldest:"Oldest",
    sort_name_az:"Name A-Z", sort_name_za:"Name Z-A",
    /* ── Companies ── */
    companies_title:"Companies", company_name:"Company Name",
    owner:"Owner", created_by:"Created By", order_no:"No.",
    confirm_delete_co:"Delete this company?",
    delete_permanent:"Data will be permanently deleted and cannot be recovered",
    search_owner:"Search owner...", no_result:"No results found",
    col_in_file:"Name found in file", col_correct:"Correct name",
    id_card_color_staff:"ID Card Color (Staff)",
    id_card_color_manager:"ID Card Color (Manager/Lead)",
    custom_color:"Custom Color", change:"Change",
    /* ── Settings ── */
    settings_title:"Settings", settings_sub:"Manage your account and system configuration",
    tab_account:"Account", tab_password:"Change Password", tab_system:"System",
    account_info:"Account Information", account_sub:"Edit your name and email",
    full_name:"Full Name", name_placeholder:"First and last name",
    current_password:"Current Password", new_password:"New Password",
    confirm_password:"Confirm Password", change_password:"Change Password",
    password_min:"New password must be at least 6 characters",
    system_settings:"System Settings",
    system_sub:"General configuration of the web application",
    sys_name_label:"System Name (shown in Sidebar)",
    /* ── Admin/Users ── */
    users_title:"System Users", users_sub:"Manage users and system permissions",
    no_users:"No users", created_at:"Created",
    edit_user:"Edit User", create_user:"Create New User",
    full_name_req:"Full Name *", password_req:"Password *",
    new_password_opt:"New password (blank = no change)",
    select_role:"Select Role",
    companies_assigned:"Companies (assigned)",
    create_company:"Create New Company",
    confirm_delete_user:"Delete this user?",
    delete_user_permanent:"User data will be permanently deleted",
    /* ── AuditLog ── */
    audit_title:"Audit Log", audit_sub:"Full system usage history",
    audit_total:"Total (this page)", audit_user:"User",
    audit_date:"Date / Time", audit_no_match:"No data matching search",
    audit_search_ph:"Search user, company, type...",
    /* ── Import ── */
    import_title:"Import Employees",
    import_sub:"Upload an Excel file to import employees with rooms, documents and permits",
    import_step1:"Step 1: Download Template and fill in data",
    download_template:"Download Excel Template",
    upload_file:"Upload File", drag_drop:"Drag file here or click to select",
    select_company:"Select Company", upload_excel:"Upload Excel File",
    reading_file:"Reading file...",
    step_upload:"Upload File", step_verify:"Verify Format",
    step_review:"Admin Review", step_done:"Complete",
    verify_result:"Format Verification Results",
    reject_reupload:"Reject & Re-upload",
    proceed_review:"Proceed → Admin Review ({n} people)",
    back_review:"Back to Review", new_upload:"New",
    import_success:"✅ Import Successful", imported:"Imported",
    skipped:"Skipped (duplicate/invalid)",
    go_employees:"Go to Employees →",
    waiting_admin:"Waiting for Super Admin Approval",
    send_admin:"📤 Send for Super Admin Approval ({n} people)",
    uploading:"Importing... {n}%", sending:"Sending...",
    people_to_import:"People to import", people_skip:"People to skip (invalid)",
    people_rooms:"People with rooms", people_docs:"People with documents",
    import_to:"Data will be saved to:", import_company:"Company to import:",
    please_select_co:"Please select a Company", no_valid_rows:"No valid rows",
    approve_import:"✅ Approve & Import {n} people",
    upload_new:"Upload New File", import_new:"Import New File",
    /* ── ID Card ── */
    idc_sub:"Manage employee ID Cards — Size 50×85mm",
    idc_select_all:"Select All", idc_print_n:"🖨 Print {n} card(s)", idc_print:"🖨 Print",
    idc_select_multi:"☑ Select Multiple to Print",
    idc_search_ph:"Search name, code, position...",
    idc_total:"Total", idc_has_card:"Has Card", idc_no_card:"No Card", idc_printed:"Printed",
    idc_return_label:"Card Return Status — Resigned Employees",
    idc_has_card_resigned:"Has Card (Resigned)", idc_returned:"Returned", idc_not_returned:"Not Returned",
    idc_selected_n:"☑ Selected {n} item(s)", idc_printable:"printable cards",
    idc_no_data:"No data found", idc_creating:"Creating...", idc_issue:"+ Issue Card",
    idc_card_returned_badge:"Card Returned", idc_saving:"Saving...", idc_receive:"📥 Receive Card",
    idc_print_card:"🖨 Print Card", idc_delete_card:"Delete Card",
    idc_confirm_del:"Delete this ID Card?",
    idc_confirm_del_sub:"The card will be deleted and the employee will have 'No Card'",
    idc_confirm_return_sub:"This will record that the employee has returned their ID Card — this action cannot be undone",
    idc_confirm_return_btn:"📥 Confirm Return",
    idc_prev:"← Prev", idc_next:"Next →",
    idc_page_info:"Page {p} / {total} ({n} records)",
    /* ── Card Requests ── */
    crq_title:"Card Requests", crq_sub:"Manage and review employee ID card requests",
    crq_new_request:"+ New Request",
    crq_search_ph:"Search request no., company, sender...",
    crq_pending:"Pending", crq_approved:"Approved", crq_issued:"Issued", crq_printed:"Printed", crq_rejected:"Rejected",
    crq_th_no:"Request No.", crq_th_sender:"Requested By", crq_th_qty:"Quantity", crq_th_date:"Date",
    crq_view:"View Details", crq_download:"Download",
    crq_employee_list:"Employee List", crq_acting:"Processing...",
    crq_download_disabled_tip:"Approve first to download", crq_downloading:"Downloading...",
    crq_start_review:"Start Review", crq_starting_review:"Opening...",
    crq_card_type:"Card Type", crq_requested_at:"Requested At",
    crq_no_match:"No requests matching search",
    /* ── Card Request Detail ── */
    crq_detail_title:"ID Request Detail",
    crq_step_submit:"Submitted", crq_step_review:"Review", crq_step_approve:"Approved",
    crq_step_complete:"Completed", crq_step_print:"Printed", crq_step_reject:"Rejected",
    crq_summary_title:"Request Summary", crq_members:"Members", crq_cards:"Cards",
    crq_purpose:"Purpose", crq_purpose_new_card:"New employee card issuance",
    crq_step_progress:"Step {n}/5 — {label}",
    crq_pending_banner:"{name} submitted this request — waiting for admin review",
    crq_approved_banner:"Approved — ID Cards have been issued to all employees in this request",
    crq_rejected_banner:"This request was rejected",
    crq_back_to_list:"← Back",
    crq_step_n_of_5:"Step {n}/5", crq_heading_pending:"Reviewing",
    crq_heading_submitted:"Request Submitted", crq_go_to_review:"Start Review →",
    crq_card_summary:"Card Type Summary", crq_print_cards:"Create Cards", crq_approved_ready:"Request approved. You can now create ID cards.",
    crq_heading_issued:"Cards Created — Ready to Print", crq_issued_banner:"Cards created — ready to view and print",
    crq_issued_title:"Created Cards", crq_total:"Total",
    crq_print_settings:"Print Settings", crq_printer_model:"Printer", crq_print_quality:"Print Quality",
    crq_print_name_cb:"Include employee name", crq_quick_preview:"Quick Preview", crq_print_all:"Print All Cards",
    crq_heading_complete:"Fully Completed", crq_complete_sub:"All done — Cards printed and activated",
    crq_printed_info:"{n} card(s) printed · {date} · by {actor}",
    crq_view_id_cards:"View ID Cards", crq_back_list:"Back to List",
    crq_review_warning:"Please review the name list and information before approving",
    crq_admin_note_label:"Admin Notes (optional)", crq_admin_note_ph:"Enter additional notes here...",
    crq_approve_short:"✓ Approve", crq_reject_short:"✕ Reject",
    crq_rollback_to_review:"← Back to Review", crq_rollback_to_approved:"← Back to Approved", crq_rollback_to_issued:"← Back to Issued",
    crq_rollback_confirm_review:"Confirm: Roll back to Review? Status will be reset to pending.", crq_rollback_confirm_approved:"Confirm: Roll back to Approved? Cards issued flag will be reset.", crq_rollback_confirm_issued:"Confirm: Roll back to Issued? Print status will be reset.",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "lo");

  const toggleLang = () => {
    const next = lang === "lo" ? "en" : "lo";
    setLang(next);
    localStorage.setItem("lang", next);
  };

  const t = (key) => translations[lang][key] ?? translations["lo"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
