import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  lo: {
    /* ── Nav ── */
    nav_dashboard:"Dashboard", nav_companies:"ບໍລິສັດ", nav_employees:"ພະນັກງານ",
    nav_idcard:"ບັດພະນັກງານ", nav_reports:"ລາຍງານ", nav_building:"Building",
    nav_import:"ນຳເຂົ້າຂໍ້ມູນ", nav_users:"ຜູ້ໃຊ້ລະບົບ", nav_audit:"Audit Log",
    nav_bulk_photo:"Upload ຮູບພ້ອມກັນ", nav_user_manual:"ຄູ່ມືການໃຊ້",
    nav_settings:"ຕັ້ງຄ່າ", nav_logout:"ອອກຈາກລະບົບ", nav_card_requests:"ຄຳຮ້ອງຂໍບັດ",
    nav_section_main:"ໃຊ້ງານປະຈຳວັນ", nav_section_manage:"ການຄຸ້ມຄອງລະບົບ",
    nav_tapinout:"ສະແກນເຂົ້າ-ອອກ", nav_about:"ກ່ຽວກັບ",
    /* ── About page ── */
    about_sub:"ຂໍ້ມູນລະບົບ ແລະ ຜູ້ພັດທະນາ", about_system_title:"ລະບົບ",
    about_company_title:"ບໍລິສັດ / ຜູ້ພັດທະນາ", about_email:"ອີເມວ", about_contact:"ຕິດຕໍ່",
    /* ── Common ── */
    search:"ຄົ້ນຫາ", add:"ເພີ່ມ", edit:"ແກ້ໄຂ", delete:"ລຶບ", save:"ບັນທຶກ",
    cancel:"ຍົກເລີກ", confirm:"ຢືນຢັນ", reload:"ໂຫຼດໃໝ່", all:"ທັງໝົດ",
    no_data:"ບໍ່ມີຂໍ້ມູນ", loading:"ກຳລັງໂຫຼດ...", back:"ກັບຄືນ",
    export_csv:"Export CSV", print:"ພິມ", status:"ສະຖານະ", company:"ບໍລິສັດ",
    all_companies:"ທຸກບໍລິສັດ", all_status:"ທຸກສະຖານະ", name:"ຊື່",
    saving:"ກຳລັງບັນທຶກ...", save_changes:"ບັນທຶກການປ່ຽນແປງ", notes:"ໝາຍເຫດ",
    notes_placeholder:"ໝາຍເຫດ...", position:"ຕຳແໜ່ງ", gender:"ເພດ",
    nationality:"ສັນຊາດ", phone:"ເບີໂທ", send_request:"ສົ່ງຄຳຂໍ",
    page_of:"ໜ້າ {p} / {total}", showing_range:"ສະແດງ {from}–{to} ຈາກ {total} ລາຍການ",
    /* ── Reports ── */
    reports_title:"ລາຍງານ", reports_sub:"ລາຍງານຂໍ້ມູນລະບົບທັງໝົດ",
    tab_employee:"ລາຍງານພະນັກງານ", tab_building:"ລາຍງານ Building",
    select_cols:"ເລືອກຖັນ", col_code:"ລະຫັດພະນັກງານ", col_name:"ຊື່ພະນັກງານ",
    col_position:"ຕຳແໜ່ງ", col_company:"ບໍລິສັດ", col_status:"ສະຖານະ",
    col_gender:"ເພດ", col_nationality:"ສັນຊາດ", col_phone:"ເບີໂທ",
    col_passport:"ເລກ Passport", col_visa:"ເລກ Visa", deselect_all:"ຍົກເລີກ",
    select_min_col:"ກະລຸນາເລືອກຢ່າງໜ້ອຍ 1 ຖັນ", showing:"ສະແດງ", of:"ຈາກ",
    items:"ລາຍການ", total:"ທັງໝົດ", active:"Active", resigned:"Resigned",
    on_leave:"On Leave", search_emp:"ຄົ້ນຫາຊື່, ລະຫັດ, ຕຳແໜ່ງ...", no_passport:"ບໍ່ມີ",
    /* ── Building ── */
    bld_title:"Building Management", bld_sub:"ຈັດການຂໍ້ມູນ {n} ຕືກ ທັງໝົດ",
    bld_office:"Office", bld_dormitory:"ຫ້ອງນອນ", bld_floors:"ຊັ້ນ",
    bld_rooms:"ຫ້ອງ", bld_available:"ວ່າງ", bld_partial:"ຍັງວ່າງ", bld_occupied:"ມີຄົນ",
    bld_maintenance:"ສ້ອມແປງ", bld_office_bld:"ອາຄານ Office",
    bld_usage:"ການໃຊ້ງານ", bld_people:"ຄົນ", bld_floor_n:"ຊັ້ນ {n}",
    bld_lobby:"Lobby / ພື້ນທີ່ສ່ວນກາງ", bld_dorm_rooms:"ຫ້ອງນອນ ({n} ຫ້ອງ)",
    bld_avail_rooms:"ຫ້ອງວ່າງ", bld_maint_short:"ສ້ອມ", bld_total_rooms:"ທັງໝົດ {n} ຫ້ອງ",
    bld_click_change:"ກົດຫ້ອງ ເພື່ອປ່ຽນສະຖານະ",
    bld_floor_n_of_bld:"{bld} — ຊັ້ນ {n}",
    bld_office_note:"ອາຄານ Office · ທັງ {n} ຊັ້ນ",
    room_n:"ຫ້ອງ {n}", room_capacity:"ຮອງຮັບ {cap} ຄົນ · ມີ {occ} ຄົນ",
    room_full:"ຫ້ອງເຕັມແລ້ວ ({cap} ຄົນ)", room_no_occupants:"ຍັງບໍ່ມີຜູ້ພັກ",
    room_residents:"ຜູ້ພັກອາໄສ ({n})", room_status:"ສະຖານະ",
    room_add_resident:"ເພີ້ມຜູ້ພັກ", room_search:"🔍 ຄົ້ນຫາຊື່ / ລະຫັດ...",
    room_add_btn:"+ ເພີ້ມເຂົ້າຫ້ອງ", room_not_found:"ບໍ່ພົບ Employee",
    total_buildings:"ຕືກທັງໝົດ", total_rooms:"ຫ້ອງທັງໝົດ",
    available:"ຫ້ອງວ່າງ", occupied:"ຫ້ອງມີຄົນ", maintenance:"ກຳລັງສ້ອມ",
    building_name:"ຊື່ຕືກ", building_type:"ປະເພດ", floors:"ຊັ້ນ",
    search_building:"ຄົ້ນຫາຊື່ຕືກ...", all_types:"ທຸກປະເພດ", dormitory:"ຫ້ອງນອນ",
    occupancy:"ອັດຕາ%", total_occupants:"ຜູ້ພັກທັງໝົດ", buildings:"ຕືກ",
    /* ── Dashboard ── */
    male:"ຊາຍ", female:"ຍິງ", resigned_total:"ຄົນອອກ (ທັງໝົດ)",
    this_month:"ເດືອນນີ້", rooms_available:"ຫ້ອງວ່າງ (Building)",
    rooms_used:"ໃຊ້ແລ້ວ {n} ຫ້ອງ",
    /* ── Employees ── */
    employees_title:"ພະນັກງານ", add_employee:"ເພີ່ມພະນັກງານ",
    employee_code:"ລະຫັດ", employee_name:"ຊື່ພະນັກງານ",
    hire_date:"ວັນທີເຂົ້າວຽກ", manage:"ຈັດການ",
    search_emp_ph:"ຄົ້ນຫາຊື່, ລະຫັດ, ຕຳແໜ່ງ...", no_employees:"ບໍ່ພົບຂໍ້ມູນພະນັກງານ",
    clear_filter:"ລ້າງ filter", view:"ເບິ່ງ",
    found_records:"ພົບ {total} ລາຍການ (ສະແດງ {from}–{to})",
    confirm_delete_emp:"ລຶບພະນັກງານນີ້ແທ້ບໍ?",
    confirm_delete_emp_admin:"ສົ່ງຄຳຂໍລຶບພະນັກງານ?",
    delete_request_info:"ຄຳຂໍຈະຖືກສົ່ງໃຫ້ Super Admin ອະນຸຍາດກ່ອນ",
    delete_info:"ຂໍ້ມູນຈະຖືກລຶບ ແລະ ບໍ່ສາມາດກູ້ຄືນໄດ້",
    all_genders:"ທຸກເພດ",
    sort_newest:"ໃໝ່ສຸດ", sort_oldest:"ເກົ່າສຸດ",
    sort_name_az:"ຊື່ A-Z", sort_name_za:"ຊື່ Z-A",
    view_table:"ສະແດງແບບຕາລາງ", view_grid:"ສະແດງແບບກາດ",
    /* ── Companies ── */
    companies_title:"ບໍລິສັດ", company_name:"ຊື່ບໍລິສັດ",
    owner:"ເຈົ້າຂອງ", created_by:"ສ້າງໂດຍ", order_no:"ລຳດັບ",
    confirm_delete_co:"ລຶບ company ນີ້ແທ້ບໍ?",
    delete_permanent:"ຂໍ້ມູນຈະຖືກລຶບຖາວອນ ແລະ ບໍ່ສາມາດກູ້ຄືນໄດ້",
    search_owner:"ຄົ້ນຫາ owner...", no_result:"ບໍ່ພົບຜົນລັບ",
    col_in_file:"ຊື່ທີ່ພົບໃນໄຟລ໌", col_correct:"ຊື່ທີ່ຖືກຕ້ອງ",
    id_card_color_staff:"ສີ ID Card (Staff)",
    id_card_color_manager:"ສີ ID Card (ຫົວໜ້າ / Manager)",
    custom_color:"ເລືອກສີ Custom", change:"ປ່ຽນ",
    /* ── Settings ── */
    settings_title:"ຕັ້ງຄ່າ", settings_sub:"ຈັດການຂໍ້ມູນ ແລະ ການຕັ້ງຄ່າລະບົບ",
    tab_account:"ບັນຊີຜູ້ໃຊ້", tab_password:"ປ່ຽນລະຫັດຜ່ານ", tab_system:"ລະບົບ",
    account_info:"ຂໍ້ມູນບັນຊີ", account_sub:"ແກ້ໄຂຊື່ ແລະ email ຂອງທ່ານ",
    full_name:"ຊື່ເຕັມ", name_placeholder:"ຊື່ ແລະ ນາມສະກຸນ",
    current_password:"ລະຫັດຜ່ານປັດຈຸບັນ", new_password:"ລະຫັດຜ່ານໃໝ່",
    confirm_password:"ຢືນຢັນລະຫັດຜ່ານ", change_password:"ປ່ຽນລະຫັດຜ່ານ",
    password_min:"ລະຫັດຜ່ານໃໝ່ຕ້ອງຢ່າງໜ້ອຍ 6 ຕົວ",
    system_settings:"ການຕັ້ງຄ່າລະບົບ",
    system_sub:"ການຕັ້ງຄ່າທົ່ວໄປຂອງ web application",
    sys_name_label:"ຊື່ລະບົບ (ສະແດງໃນ Sidebar)",
    admin_email_label:"Admin Email", timezone_label:"ເຂດເວລາ", feature_toggles_title:"Feature Toggles",
    about_settings_title:"ໜ້າ About", about_settings_sub:"ຂໍ້ມູນບໍລິສັດ/ຜູ້ພັດທະນາທີ່ສະແດງຢູ່ໜ້າ About",
    about_company_name_label:"ຊື່ບໍລິສັດ", about_email_label:"ອີເມວ",
    about_contact_label:"ຕິດຕໍ່ (ຊື່ ເບີໂທ)",
    tab_general:"ທົ່ວໄປ", tab_notifications:"ການແຈ້ງເຕືອນ", tab_security:"ຄວາມປອດໄພ",
    tab_appearance:"ໂຕປະກອບ", tab_language:"ພາສາ", tab_backup:"Backup & Export",
    feat_audit_logging:"Audit Logging", feat_audit_logging_desc:"ບັນທຶກທຸກການກະທຳຂອງຜູ້ໃຊ້ໄວ້ໃນ Audit Log",
    feat_expiry_alerts:"ແຈ້ງເຕືອນໝົດອາຍຸ Permit/Visa", feat_expiry_alerts_desc:"ແຈ້ງເຕືອນຜູ້ດູແລລະບົບກ່ອນໝົດອາຍຸ",
    feat_expiry_alert_days_label:"ແຈ້ງເຕືອນກ່ອນໝົດອາຍຸ (ມື້)", feat_check_now:"ກວດສອບດຽວນີ້",
    feat_2fa:"Two-Factor Authentication", feat_2fa_desc:"ບັງຄັບໃຊ້ 2FA ສຳລັບ login ຂອງ Super Admin",
    feat_auto_backup:"Automatic Data Backup", feat_auto_backup_desc:"ສຳຮອງຂໍ້ມູນອັດຕະໂນມັດທຸກມື້",
    super_admin_only:"ສະເພາະ Super Admin ທີ່ແກ້ໄຂໄດ້", coming_soon:"ກຳລັງພັດທະນາ — ມາໄວໆນີ້",
    backup_sleep_note:"ໝາຍເຫດ: Backup ຈະແລ່ນອັດຕະໂນມັດໃນຄັ້ງທຳອິດທີ່ມີຄົນເຂົ້າໃຊ້ລະບົບຫຼັງເວລາທີ່ກຳນົດ — Render free tier ບໍ່ສາມາດແລ່ນ background job ໃນຂະນະທີ່ server ນອນຢູ່",
    backup_run_now:"Backup ດຽວນີ້", backup_history_title:"ປະຫວັດ Backup",
    backup_col_date:"ວັນທີ", backup_col_size:"ຂະໜາດ", backup_col_trigger:"ປະເພດ", backup_download:"ດາວໂຫລດ",
    backup_success:"Backup ສຳເລັດ",
    backup_restore:"ກູ້ຄືນ", backup_restoring:"ກຳລັງກູ້ຄືນ...",
    restore_type_confirm:"ພິມ RESTORE ເພື່ອຢືນຢັນ",
    restore_confirm_btn:"ຢືນຢັນກູ້ຄືນ", restore_confirm_mismatch:"ກະລຸນາພິມ RESTORE ໃຫ້ຖືກຕ້ອງ",
    restore_warning:"⚠️ ການກູ້ຄືນຈະລຶບຂໍ້ມູນປະຈຸບັນທັງໝົດ ແລະ ແທນທີ່ດ້ວຍຂໍ້ມູນຈາກ backup ນີ້ — ລະບົບຈະສ້າງ backup ສຳຮອງຂອງສະພາບປະຈຸບັນໄວ້ກ່ອນ ເຜື່ອກູ້ຄືນຜິດ",
    restore_success:"ກູ້ຄືນຂໍ້ມູນສຳເລັດ", restore_failed:"ກູ້ຄືນບໍ່ສຳເລັດ",
    appearance_upload_logo:"ອັບໂຫລດ Logo", appearance_remove_logo:"ລຶບ Logo",
    tfa_status_on:"✅ ເປີດໃຊ້ງານແລ້ວ", tfa_status_off:"ຍັງບໍ່ໄດ້ເປີດໃຊ້ງານ",
    tfa_enable_btn:"ເປີດໃຊ້ 2FA", tfa_disable_btn:"ປິດໃຊ້ 2FA", tfa_confirm_disable:"ຢືນຢັນປິດ 2FA",
    tfa_disabled_ok:"ປິດ 2FA ສຳເລັດ", tfa_require_label:"ບັງຄັບໃຊ້ 2FA (Super Admin)",
    tfa_require_desc:"ບັງຄັບໃຫ້ Super Admin ທຸກຄົນຕັ້ງ 2FA ກ່ອນເຂົ້າລະບົບ",
    /* ── Admin/Users ── */
    users_title:"ຜູ້ໃຊ້ລະບົບ", users_sub:"ຈັດການ users ແລະ ສິດໃຊ້ງານລະບົບ",
    no_users:"ບໍ່ມີ users", created_at:"ສ້າງເມື່ອ",
    edit_user:"ແກ້ໄຂຂໍ້ມູນ user", create_user:"ສ້າງ user ໃໝ່ໃນລະບົບ",
    full_name_req:"ຊື່ເຕັມ *", password_req:"ລະຫັດຜ່ານ *",
    new_password_opt:"ລະຫັດຜ່ານໃໝ່ (ຍ່ອງຖ້ານ = ບໍ່ປ່ຽນ)",
    select_role:"ເລືອກ Role",
    companies_assigned:"Companies (ທີ່ assign)",
    create_company:"ສ້າງ Company ໃໝ່",
    confirm_delete_user:"ລຶບ user ນີ້ແທ້ບໍ?",
    delete_user_permanent:"ຂໍ້ມູນ user ຈະຖືກລຶບຖາວອນ",
    /* ── AuditLog ── */
    audit_title:"Audit Log", audit_sub:"ປະຫວັດການໃຊ້ງານລະບົບທັງໝົດ",
    audit_total:"ທັງໝົດ (ໜ້ານີ້)", audit_user:"ຜູ້ໃຊ້",
    audit_date:"ວັນທີ / ເວລາ", audit_no_match:"ບໍ່ມີຂໍ້ມູນທີ່ກົງກັບການຄົ້ນຫາ",
    audit_search_ph:"ຄົ້ນຫາຊື່ user, company, ປະເພດ...",
    /* ── Import ── */
    import_title:"ນຳເຂົ້າພະນັກງານ",
    import_sub:"ອັບໂຫລດໄຟລ໌ Excel ເພື່ອນຳເຂົ້າພະນັກງານ ພ້ອມ ຫ້ອງ, ເອກະສານ ແລະ ໃບອະນຸຍາດ",
    import_step1:"ຂັ້ນຕອນທີ 1: ດາວໂຫລດ Template ແລ້ວຕື່ມຂໍ້ມູນ",
    download_template:"ດາວໂຫລດ Template Excel",
    upload_file:"ອັບໂຫລດໄຟລ໌", drag_drop:"ລາກໄຟລ໌ມາວາງ ຫຼື ກົດເພື່ອເລືອກ",
    select_company:"ເລືອກ Company", upload_excel:"ອັບໂຫລດໄຟລ໌ Excel",
    reading_file:"ກຳລັງອ່ານໄຟລ໌...",
    step_upload:"ອັບໂຫລດໄຟລ໌", step_verify:"ຕຣວດສອບ Format",
    step_review:"Admin ກວດສອບ", step_done:"ສຳເລັດ",
    verify_result:"ຜົນການຕຣວດສອບ Format",
    reject_reupload:"Reject ແລະ Upload ໃໝ່",
    proceed_review:"ດຳເນີນການ → Admin ກວດສອບ ({n} ຄົນ)",
    back_review:"ກັບໄປກວດສອບ", new_upload:"ໃໝ່",
    import_success:"✅ Import ສຳເລັດ", imported:"ນຳເຂົ້າສຳເລັດ",
    skipped:"ຂ້າມ (ຊໍ້າ/ຜິດ)",
    go_employees:"ໄປໜ້າພະນັກງານ →",
    waiting_admin:"ລໍຖ້າ Super Admin ອະນຸມັດ",
    send_admin:"📤 ສົ່ງຂໍ Super Admin ອະນຸມັດ ({n} ຄົນ)",
    uploading:"ກຳລັງນຳເຂົ້າ... {n}%", sending:"ກຳລັງສົ່ງ...",
    people_to_import:"ຄົນທີ່ຈະນຳເຂົ້າ", people_skip:"ຄົນທີ່ຈະຂ້າມ (ຜິດ)",
    people_rooms:"ຄົນທີ່ມີຫ້ອງ", people_docs:"ຄົນທີ່ມີເອກະສານ",
    import_to:"ຂໍ້ມູນຈະຖືກບັນທຶກໃສ່:", import_company:"Company ທີ່ຈະນຳເຂົ້າ:",
    please_select_co:"ກະລຸນາເລືອກ Company", no_valid_rows:"ບໍ່ມີແຖວທີ່ຖືກຕ້ອງ",
    approve_import:"✅ Approve ແລະ Import {n} ຄົນ",
    upload_new:"ສົ່ງໄຟລ໌ໃໝ່", import_new:"ນຳເຂົ້າໄຟລ໌ໃໝ່",
    /* ── ID Card ── */
    idc_sub:"ຈັດການ ID Card ຂອງພະນັກງານ — ຂະໜາດ 50×85mm",
    idc_select_all:"ເລືອກທັງໝົດ", idc_print_n:"🖨 ພິມ {n} ບັດ", idc_print:"🖨 ພິມ",
    idc_select_multi:"☑ ເລືອກພິມຫຼາຍບັດ",
    idc_search_ph:"ຄົ້ນຫາຊື່, ລະຫັດ, ຕຳແໜ່ງ...",
    idc_total:"ທັງໝົດ", idc_has_card:"ມີ Card", idc_no_card:"ບໍ່ມີ Card", idc_printed:"ພິມແລ້ວ",
    idc_return_label:"ສະຖານະການຄືນບັດ — ພະນັກງານທີ່ອອກວຽກ",
    idc_has_card_resigned:"ມີບັດ (ອອກວຽກ)", idc_returned:"ຄືນແລ້ວ", idc_not_returned:"ຍັງບໍ່ທັນຄືນ",
    idc_selected_n:"☑ ເລືອກໄວ້ {n} ລາຍການ", idc_printable:"ບັດທີ່ພິມໄດ້",
    idc_no_data:"ບໍ່ມີຂໍ້ມູນ", idc_creating:"ກຳລັງສ້າງ...", idc_issue:"+ ສ້າງ Card",
    idc_card_returned_badge:"ຄືນບັດແລ້ວ", idc_saving:"ກຳລັງບັນທຶກ...", idc_receive:"📥 ຮັບຄືນບັດ",
    idc_print_card:"🖨 ພິມ Card", idc_delete_card:"ລຶບ Card",
    idc_confirm_del:"ລຶບ ID Card ນີ້ແທ້ບໍ?",
    idc_confirm_del_sub:"Card ຈະຖືກລຶບ ແລະ ພະນັກງານຈະກັບໄປ 'ບໍ່ມີ Card'",
    idc_confirm_return_sub:"ຈະບັນທຶກວ່າພະນັກງານໄດ້ຄືນ ID Card ແລ້ວ — ການກະທຳນີ້ບໍ່ສາມາດຍ້ອນຄືນໄດ້",
    idc_confirm_return_btn:"📥 ຢືນຢັນຮັບຄືນ",
    idc_prev:"← ກ່ອນ", idc_next:"ຕໍ່ໄປ →",
    idc_page_info:"ໜ້າ {p} / {total} ({n} ລາຍການ)",
    /* ── Card Requests ── */
    crq_title:"ຄຳຮ້ອງຂໍບັດ", crq_sub:"ຈັດການ ແລະ ກວດສອບຄຳຂໍອອກບັດພະນັກງານ",
    crq_new_request:"+ ສົ່ງຄຳຂໍໃໝ່",
    crq_search_ph:"ຄົ້ນຫາເລກຄຳຂໍ, ບໍລິສັດ, ຜູ້ສົ່ງ...",
    crq_pending:"ລໍຖ້າດຳເນີນ", crq_approved:"ອະນຸມັດແລ້ວ", crq_issued:"ສຳບັດແລ້ວ", crq_printed:"ພິມແລ້ວ", crq_completed:"ສຳເລັດ", crq_rejected:"ປະຕິເສດ",
    crq_th_no:"ເລກຄຳຂໍ", crq_th_sender:"ຜູ້ສົ່ງຄຳຂໍ", crq_th_qty:"ຈຳນວນ", crq_th_date:"ວັນທີ",
    crq_view:"ເບິ່ງລາຍລະອຽດ", crq_download:"ດາວໂຫລດ",
    crq_employee_list:"ລາຍຊື່ພະນັກງານ", crq_acting:"ກຳລັງດຳເນີນການ...",
    crq_download_disabled_tip:"ອະນຸມັດກ່ອນຈິ່ງດາວໂຫລດໄດ້", crq_downloading:"ກຳລັງດາວໂຫລດ...",
    crq_start_review:"ເລີ່ມກວດສອບ", crq_starting_review:"ກຳລັງເປີດ...",
    crq_card_type:"ປະເພດບັດ", crq_requested_at:"ສົ່ງເມື່ອ",
    crq_no_match:"ບໍ່ມີຄຳຮ້ອງທີ່ກົງກັບການຄົ້ນຫາ",
    /* ── Card Request Detail ── */
    crq_detail_title:"ລາຍລະອຽດຄຳຮ້ອງ ID",
    crq_step_submit:"ສົ່ງຄຳຂໍ", crq_step_review:"ກວດສອບ", crq_step_approve:"ອະນຸມັດ",
    crq_step_complete:"ສຳເລັດ", crq_step_print:"ພິມບັດ", crq_step_reject:"ປະຕິເສດ",
    crq_step_review_approve:"ກວດສອບ & ອະນຸມັດ", crq_step_create_print:"ສ້າງ & ພິມບັດ",
    crq_summary_title:"ສະຫຸບຄຳຂໍ", crq_members:"ສະມາຊິກ", crq_cards:"ໃບ",
    crq_purpose:"ຈຸດປະສົງ", crq_purpose_new_card:"ອອກບັດພະນັກງານໃໝ່",
    crq_step_progress:"ຂັ້ນຕອນ {n}/3 — {label}",
    crq_step_n_of_3:"ຂັ້ນຕອນ {n}/3",
    crq_pending_banner:"{name} ໄດ້ສົ່ງຄຳຂໍ — ກະລຸນາກວດສອບລາຍຊື່ ແລະ ຂໍ້ມູນກ່ອນອະນຸມັດ",
    crq_approved_banner:"ອະນຸມັດແລ້ວ — ອອກບັດ ID Card ໃຫ້ພະນັກງານທັງໝົດໃນຄຳຂໍນີ້ແລ້ວ",
    crq_rejected_banner:"ຄຳຂໍນີ້ຖືກປະຕິເສດ",
    crq_back_to_list:"← ກັບຄືນ",
    crq_step_n_of_5:"ຂັ້ນຕອນ {n}/3", crq_heading_pending:"ກຳລັງກວດສອບ",
    crq_heading_review_approve:"ກວດສອບ & ອະນຸມັດຄຳຮ້ອງ", crq_heading_create_print:"ສ້າງ & ພິມບັດ",
    crq_heading_submitted:"ຄຳຂໍຖືກສົ່ງເຂົ້າມາແລ້ວ", crq_go_to_review:"ເລີ່ມກວດສອບ →",
    crq_card_summary:"ສະຫຸບປະເພດບັດ", crq_print_cards:"ສ້າງບັດ", crq_approved_ready:"ຄຳຂໍໄດ້ຮັບການອະນຸມັດແລ້ວ. ສາມາດສ້າງບັດ ID ໄດ້",
    crq_heading_issued:"ສ້າງບັດແລ້ວ — ສຳພິມ", crq_issued_banner:"ສ້າງບັດສຳເລັດ — ສາມາດເບິ່ງ ແລະ ສຳພິມໄດ້ເລີຍ",
    crq_issued_title:"ບັດທີ່ສ້າງແລ້ວ", crq_total:"ລວມ",
    crq_print_settings:"ຕັ້ງການພິມ", crq_printer_model:"ເລືອກພິມ", crq_print_quality:"ຄຸນນະພາບການພິມ",
    crq_print_name_cb:"ພິມລາຍຊື່ພະນັກງານ", crq_quick_preview:"ເບິ່ງຢ່າງດ່ວນ", crq_print_all:"ພິມບັດທັງໝົດ",
    crq_heading_complete:"ສຳເລັດສົມບູນ", crq_complete_sub:"ສຳເລັດສົມບູນ — ບັດຖືກພິມ ແລະ ເປີດໃຊ້ງານແລ້ວ",
    crq_printed_info:"ບັດ {n} ໃບ ໄດ້ຖືກພິມ · {date} · ໂດຍ {actor}",
    crq_view_id_cards:"ເບິ່ງ ID Cards", crq_back_list:"ຍ້ອນກັບ",
    crq_review_warning:"ກະລຸນາກວດສອບລາຍຊື່ ແລະ ນາມຂໍ້ມູນກ່ອນອະນຸມັດ",
    crq_admin_note_label:"ໝາຍເຫດຜູ້ດູແລ (ບໍ່ບັງຄັບ)", crq_admin_note_ph:"ໃສ່ໝາຍເຫດເພີ່ມເຕີມບ່ອນນີ້...",
    crq_approve_short:"✓ ອະນຸມັດ", crq_reject_short:"✕ ປະຕິເສດ",
    crq_rollback_to_review:"← ຍ້ອນໄປ ກວດສອບ", crq_rollback_to_approved:"← ຍ້ອນໄປ ອະນຸມັດ", crq_rollback_to_issued:"← ຍ້ອນໄປ ສ້າງບັດ",
    crq_rollback_confirm_review:"ຢືນຢັນ: ຍ້ອນກັບໄປ ກວດສອບ? ສະຖານະຈະຖືກ reset ເປັນ pending.", crq_rollback_confirm_approved:"ຢືນຢັນ: ຍ້ອນກັບໄປ ອະນຸມັດ? cards_issued ຈະຖືກ reset.", crq_rollback_confirm_issued:"ຢືນຢັນ: ຍ້ອນກັບໄປ ສ້າງບັດ? ສະຖານະພິມຈະຖືກ reset.",
    /* ── AddEmployee ── */
    ae_edit_title:"ແກ້ໄຂຂໍ້ມູນພະນັກງານ", ae_edit_sub:"ຕື່ມຂໍ້ມູນເພື່ອອັບເດດພະນັກງານ",
    ae_add_sub:"ຕື່ມຂໍ້ມູນເພື່ອເພີ່ມພະນັກງານໃໝ່",
    section_basic_info:"ຂໍ້ມູນພື້ນຖານ", section_additional:"ຂໍ້ມູນເພີ່ມເຕີມ",
    section_address:"ທີ່ຢູ່ / ຂໍ້ມູນ Profile",
    first_name:"ຊື່", last_name:"ນາມສະກຸນ",
    upload_photo:"ອັບໂຫລດຮູບ", auto_generate:"ສ້າງອັດຕະໂນມັດ",
    select_gender:"ເລືອກເພດ", opt_other:"ອື່ນໆ",
    select_emp_type:"ເລືອກປະເພດພະນັກງານ",
    opt_fulltime:"ເຕັມເວລາ", opt_parttime:"ບາງເວລາ", opt_contract:"ສັນຍາ", opt_intern:"ຝຶກງານ",
    opt_inactive:"ບໍ່ເຄື່ອນໄຫວ",
    province:"ແຂວງ", district:"ເມືອງ", village:"ບ້ານ",
    update_employee:"ອັບເດດພະນັກງານ", notes_long_ph:"ໃສ່ໝາຍເຫດເພີ່ມເຕີມ...",
    office_loc_lbl:"🏢 ທີ່ຕັ້ງ Office (ບ່ອນເຮັດວຽກ)", dormitory_lbl:"🛏️ ທີ່ພັກ (Dormitory)",
    office_bld_lbl:"ຕືກ Office", office_floor_lbl:"ຊັ້ນ Office", office_room_lbl:"ຫ້ອງ Office",
    dorm_bld_lbl:"ຕືກທີ່ພັກ", floor_lbl:"ຊັ້ນ", room_lbl:"ຫ້ອງ",
    sel_office_bld:"-- ເລືອກຕືກ Office --", sel_floor_opt:"-- ເລືອກຊັ້ນ --",
    sel_room_opt:"-- ເລືອກຫ້ອງ --", not_assigned_opt:"-- ບໍ່ໄດ້ກຳນົດ --",
    floor_n:"ຊັ້ນ {n}", room_full_tag:"(ເຕັມ)",
    err_sel_co_first:"ກະລຸນາເລືອກ Company ກ່ອນ", err_code_fetch:"ດຶງ code ບໍ່ໄດ້",
    err_firstname:"ກະລຸນາໃສ່ First Name", err_lastname:"ກະລຸນາໃສ່ Last Name",
    err_sel_company:"ກະລຸນາເລືອກ Company", err_email_fmt:"ຮູບແບບ Email ບໍ່ຖືກຕ້ອງ",
    edit_req_sent:"ສົ່ງຄຳຂໍແກ້ໄຂໄປຍັງ Super Admin ແລ້ວ — ລໍຖ້າການອະນຸຍາດ",
    emp_updated:"ອັບເດດພະນັກງານສຳເລັດ", emp_added:"ເພີ່ມພະນັກງານສຳເລັດ",
    save_failed_msg:"ບັນທຶກບໍ່ສຳເລັດ",
    /* ── Admin/Users ── */
    users_page_title:"ຜູ້ໃຊ້ ແລະ ສິດ", col_actions:"ຈັດການ",
    add_user_btn:"+ ເພີ່ມ User", edit_user_title:"ແກ້ໄຂ User", add_user_title:"ເພີ່ມ User",
    update_btn:"ອັບເດດ", create_user_btn:"ສ້າງ User",
    new_co_ph:"ຊື່ Company ໃໝ່...", cancel_new_co_btn:"✕ ຍົກເລີກ",
    create_new_co_btn:"+ ສ້າງ Company ໃໝ່", sel_role_opt:"-- ເລືອກ Role --",
    load_failed:"ໂຫຼດຂໍ້ມູນບໍ່ໄດ້", fill_required:"ກະລຸນາໃສ່ຂໍ້ມູນໃຫ້ຄົບ",
    please_enter_pw:"ກະລຸນາໃສ່ລະຫັດຜ່ານ",
    user_updated_ok:"ອັບເດດ user ສຳເລັດ", user_created_ok:"ສ້າງ user ສຳເລັດ",
    user_deleted_ok:"ລຶບ user ສຳເລັດ", delete_failed_msg:"ລຶບບໍ່ສຳເລັດ",
    co_created_ok:"ສ້າງ Company ສຳເລັດ", co_create_fail:"ສ້າງ Company ບໍ່ສຳເລັດ",
    /* ── BulkPhotoUpload ── */
    bpu_sub:"ອັບໂຫລດຮູບໜ້າພະນັກງານຫຼາຍຄົນພ້ອມກັນ",
    bpu_how_to:"ວິທີໃຊ້:", bpu_name_match:"ຊື່ໄຟລ໌ຕ້ອງກົງກັບ",
    bpu_drag_text:"ລາກ & ວາງຮູບທີ່ນີ້ ຫຼື ກົດເພື່ອເລືອກ",
    bpu_supports:"ຮອງຮັບ JPG, PNG, WEBP — ສູງສຸດ 5MB/ຮູບ",
    bpu_selected_n:"ເລືອກ {n} ຮູບແລ້ວ", bpu_click_change:"ກົດເພື່ອປ່ຽນ / ເພີ່ມຮູບ",
    bpu_uploading:"⏳ ກຳລັງ upload...", bpu_upload_n:"📤 Upload {n} ຮູບ",
    bpu_clear:"ລ້າງ", bpu_success_n:"✅ ສຳເລັດ: {n}", bpu_notfound_n:"❌ ບໍ່ພົບ Code: {n}",
    bpu_error_n:"⚠️ Error: {n}", bpu_ok_heading:"✅ ອັບໂຫລດສຳເລັດ",
    bpu_nf_heading:"❌ ບໍ່ພົບ Employee Code ນີ້ໃນລະບົບ",
    bpu_new_batch:"+ Upload ຊຸດໃໝ່", bpu_img_only:"ເລືອກສະເພາະໄຟລ໌ຮູບ",
    bpu_toast_ok:"ອັບໂຫລດສຳເລັດ {n}/{total} ຮູບ", bpu_toast_err:"ເກີດຂໍ້ຜິດພາດ",
    /* ── Settings ── */
    st_backend_api:"Backend API URL", st_edit_env:"ແກ້ໄຂໃນໄຟລ໌ .env (VITE_API_URL)",
    save_btn:"ບັນທຶກ", st_update_ok:"ອັບເດດຂໍ້ມູນສຳເລັດ", st_update_fail:"ອັບເດດບໍ່ສຳເລັດ",
    st_pw_ok:"ປ່ຽນລະຫັດຜ່ານສຳເລັດ", st_pw_fail:"ປ່ຽນລະຫັດຜ່ານບໍ່ສຳເລັດ",
    st_sys_ok:"ບັນທຶກການຕັ້ງຄ່າສຳເລັດ", st_save_fail:"ບັນທຶກບໍ່ສຳເລັດ",
    st_fill_all:"ກະລຸນາໃສ່ຂໍ້ມູນໃຫ້ຄົບ", st_pw_mismatch:"ລະຫັດຜ່ານໃໝ່ບໍ່ຕົງກັນ",
    /* ── EmployeeDetail tabs ── */
    ed_sub:"ຈັດການ ແລະ ຈັດຮຽງຂໍ້ມູນພະນັກງານ",
    tab_basic_info:"ຂໍ້ມູນພື້ນຖານ", tab_profile:"ໂປຣໄຟລ໌",
    tab_documents:"ເອກະສານ", tab_permits:"Permits",
    tab_timeline:"ປະຫວັດ", tab_emp_cards:"ບັດພະນັກງານ",
    /* ── BasicInfoTab ── */
    lbl_date_of_birth:"ວັນເດືອນປີເກີດ", lbl_resigned_date:"ວັນທີອອກວຽກ",
    lbl_resigned_reason:"ເຫດຜົນອອກວຽກ", lbl_created_at:"ສ້າງເມື່ອ", lbl_updated_at:"ອັບເດດເມື່ອ",
    /* ── ProfileTab ── */
    pf_address:"📍 ທີ່ຢູ່", pf_employment:"💼 ການຈ້າງງານ",
    pf_office_loc:"🏢 ທີ່ຕັ້ງ Office", pf_dormitory:"🛏️ ທີ່ພັກ (Dormitory)",
    pf_notes_sec:"📝 ໝາຍເຫດ",
    pf_province:"ແຂວງ (Province)", pf_district:"ເມືອງ (District)", pf_village:"ບ້ານ (Village)",
    pf_hire_date:"ວັນທີເຂົ້າວຽກ", pf_emp_type:"ປະເພດພະນັກງານ",
    pf_field_col:"ຊ່ອງຂໍ້ມູນ", pf_value_col:"ຄ່າ",
    /* ── DocumentsTab ── */
    doc_title:"ເອກະສານ", doc_add_btn:"+ ເພີ້ມເອກະສານ",
    doc_type_lbl:"ປະເພດ", doc_name_lbl:"ຊື່ເອກະສານ *",
    doc_expiry_lbl:"ວັນໝົດອາຍຸ", doc_file_lbl:"ໄຟລ໌ (PDF / ຮູບ)",
    doc_file_btn:"ເລືອກໄຟລ໌", doc_photo_col:"ຮູບ",
    doc_detail_col:"ຊື່ / ລາຍລະອຽດ", doc_uploaded_by:"ອັບໂຫລດໂດຍ",
    doc_no_data:"ຍັງບໍ່ມີເອກະສານ",
    doc_ph_name:"ເຊັ່ນ: Passport No. AB123456", doc_ph_notes:"ໝາຍເຫດເພີ້ມເຕີມ",
    doc_del_preview:"✕ ລຶບ", doc_del_btn:"ລຶບ",
    err_doc_name:"ກະລຸນາໃສ່ຊື່ເອກະສານ", doc_saved:"ບັນທຶກເອກະສານສຳເລັດ",
    doc_save_fail:"ບໍ່ສາມາດບັນທຶກໄດ້", doc_del_confirm:"ລຶບເອກະສານນີ້ແທ້ບໍ?",
    doc_deleted:"ລຶບສຳເລັດ", doc_del_fail:"ລຶບບໍ່ໄດ້",
    /* ── PermitsTab ── */
    permit_title:"Permits / Visa", permit_add_btn:"+ ເພີ້ມ Permit",
    permit_type_lbl:"ປະເພດ *", permit_number_lbl:"ເລກ Permit",
    permit_status_lbl:"ສະຖານະ", permit_issued_lbl:"ວັນທີອອກ",
    permit_expiry_lbl:"ວັນໝົດອາຍຸ", permit_file_lbl:"ຮູບເອກະສານ (Visa / Passport)",
    permit_photo_col:"ຮູບ", permit_no_col:"ເລກ Permit",
    permit_issued_col:"ວັນທີອອກ", permit_expiry_col:"ວັນໝົດອາຍຸ",
    permit_no_data:"ຍັງບໍ່ມີ Permit",
    permit_ph_number:"ເຊັ່ນ: WP-2025-00123", permit_ph_notes:"ໝາຍເຫດ...",
    permit_del_btn:"ລຶບ", permit_edit_btn:"ແກ້", permit_edit_save:"ແກ້ໄຂ",
    err_permit_type:"ກະລຸນາໃສ່ປະເພດ", permit_edit_ok:"ແກ້ໄຂສຳເລັດ",
    permit_add_ok:"ເພີ້ມ Permit ສຳເລັດ", permit_save_fail:"ບໍ່ສາມາດບັນທຶກໄດ້",
    permit_del_confirm:"ລຶບ Permit ນີ້ແທ້ບໍ?", permit_deleted:"ລຶບສຳເລັດ",
    permit_del_fail:"ລຶບບໍ່ໄດ້",
    /* ── TimelineTab ── */
    tl_title:"ປະຫວັດການປ່ຽນແປງ", tl_add_btn:"+ ບັນທຶກເຫດການ",
    tl_event_type:"ປະເພດເຫດການ", tl_old_value:"ຄ່າເກົ່າ", tl_new_value:"ຄ່າໃໝ່",
    tl_old_ph:"ຄ່າກ່ອນປ່ຽນ...", tl_new_ph:"ຄ່າຫລັງປ່ຽນ...",
    tl_notes_ph:"ລາຍລະອຽດເພີ້ມເຕີມ...", tl_by:"ໂດຍ:", tl_no_data:"ຍັງບໍ່ມີປະຫວັດ",
    err_tl_details:"ກະລຸນາໃສ່ລາຍລະອຽດ", tl_saved:"ບັນທຶກສຳເລັດ",
    tl_save_fail:"ບໍ່ສາມາດບັນທຶກໄດ້",
    /* ── ExpiryBadge ── */
    exp_expired:"(ໝົດອາຍຸ)", exp_days_left:"(ຍັງ {d} ມື້)",
    /* ── EmployeeCardDetail ── */
    ecd_title:"ບັດພະນັກງານ", ecd_sub:"ເບິ່ງລາຍລະອຽດ ແລະ ສະຖານະ ID Card ຂອງພະນັກງານ",
    ecd_preview_title:"ຕົວຢ່າງ ID Card", ecd_preview_sub:"ນີ້ຄືລັກສະນະ ID Card ທີ່ຈະພິມ",
    ecd_download:"ດາວໂຫລດ", ecd_print:"ພິມ Card",
    ecd_card_info:"ຂໍ້ມູນ Card", ecd_no_history:"ບໍ່ມີ History",
    ecd_card_history:"ປະຫວັດ Card", ecd_card_no:"ເລກ Card",
    ecd_emp_name:"ຊື່ພະນັກງານ", ecd_issued_by:"ອອກໂດຍ",
    ecd_issued_at:"ອອກເມື່ອ", ecd_printed_at:"ພິມເມື່ອ",
    ecd_returned_at:"ຄືນເມື່ອ", ecd_returned_by:"ຄືນໂດຍ",
    ecd_revoked_at:"ຍົກເລີກເມື່ອ", ecd_revoked_reason:"ເຫດຜົນ",
    ecd_no_card:"ບໍ່ມີ Card", ecd_hist_dt:"ວັນທີ / ເວລາ",
    ecd_hist_by:"ໂດຍ", ecd_hist_remark:"ໝາຍເຫດ",
    toast_load_fail:"ໂຫຼດຂໍ້ມູນ Card ບໍ່ໄດ້", toast_print_ok:"ພິມ Card ສຳເລັດ",
    /* ── ImportApproval ── */
    ia_title:"ອະນຸມັດ Import ພະນັກງານ",
    ia_sub:"ກວດສອບ ແລະ ອະນຸມັດ/ປະຕິເສດ ຄຳຂໍ Import ຈາກ Company Admin",
    ia_status_pending:"ລໍຖ້າ", ia_status_approved:"ອະນຸມັດ", ia_status_rejected:"ປະຕິເສດ",
    ia_all:"ທັງໝົດ", ia_no_batch:"ບໍ່ມີລາຍການ", ia_submitted_by:"ສົ່ງໂດຍ",
    ia_valid:"ຖືກຕ້ອງ", ia_invalid_skip:"ຜິດ/ຂ້າມ", ia_total:"ທັງໝົດ",
    ia_reject_reason_lbl:"ເຫດຜົນປະຕິເສດ",
    ia_preview_rows:"ຂໍ້ມູນ (ສະແດງ 10 ແຖວ)",
    ia_confirm_reject:"ຢືນຢັນປະຕິເສດ", ia_reject_btn:"✗ ປະຕິເສດ",
    ia_processing:"ກຳລັງດຳເນີນ...", ia_select_batch:"ເລືອກ Batch ທາງຊ້າຍ ເພື່ອກວດສອບ",
    ia_and_more:"... ແລະ {n} ແຖວເພີ້ມ", ia_reason_ph:"ໃສ່ເຫດຜົນ (ຖ້າມີ)...",
    ia_approve_confirm:"ອະນຸມັດ Import {n} ຄົນ ແທ້ບໍ?",
    ia_load_fail:"ໂຫລດບໍ່ໄດ້",
    ia_approve_ok:"ອະນຸມັດສຳເລັດ — ນຳເຂົ້າ {n} ຄົນ",
    ia_approve_fail:"ອະນຸມັດບໍ່ສຳເລັດ", ia_reject_ok:"ປະຕິເສດ Batch ແລ້ວ",
    ia_reject_fail:"ປະຕິເສດບໍ່ສຳເລັດ",
    /* ── TapInOut ── */
    tio_title:"ປະຫວັດສະແກນເຂົ້າ-ອອກ",
    tio_sub:"ກວດສອບປະຫວັດການແທັບ/ສະແກນເຂົ້າ-ອອກວຽກຂອງພະນັກງານ ຕາມວັນ ເດືອນ ປີ",
    tio_stat_ontime:"ມາທັນເວລາ", tio_stat_late:"ມາຊ້າ", tio_stat_working:"ກຳລັງເຮັດວຽກ",
    tio_search_ph:"ຄົ້ນຫາຊື່ ຫຼື ລະຫັດພະນັກງານ...",
    tio_col_employee:"ພະນັກງານ", tio_col_date:"ວັນທີ", tio_col_timein:"ເວລາເຂົ້າ",
    tio_col_timeout:"ເວລາອອກ", tio_col_hours:"ຊົ່ວໂມງເຮັດວຽກ", tio_col_method:"ວິທີສະແກນ",
    tio_no_data:"ບໍ່ພົບຂໍ້ມູນການສະແກນເຂົ້າ-ອອກ", tio_no_match:"ບໍ່ພົບຂໍ້ມູນທີ່ກົງກັບການກອງ",
    tio_still_working:"ກຳລັງເຮັດວຽກ",
  },

  en: {
    /* ── Nav ── */
    nav_dashboard:"Dashboard", nav_companies:"Companies", nav_employees:"Employees",
    nav_idcard:"ID Cards", nav_reports:"Reports", nav_building:"Building",
    nav_import:"Import Data", nav_users:"System Users", nav_audit:"Audit Log",
    nav_bulk_photo:"Bulk Photo Upload", nav_user_manual:"User Manual",
    nav_settings:"Settings", nav_logout:"Log Out", nav_card_requests:"Card Request",
    nav_tapinout:"Tap In-Out", nav_about:"About",
    nav_section_main:"DAILY USE", nav_section_manage:"SYSTEM MANAGEMENT",
    /* ── About page ── */
    about_sub:"System and developer information", about_system_title:"System",
    about_company_title:"Company / Developer", about_email:"Email", about_contact:"Contact",
    /* ── Common ── */
    search:"Search", add:"Add", edit:"Edit", delete:"Delete", save:"Save",
    cancel:"Cancel", confirm:"Confirm", reload:"Reload", all:"All",
    no_data:"No data found", loading:"Loading...", back:"Back",
    export_csv:"Export CSV", print:"Print", status:"Status", company:"Company",
    all_companies:"All Companies", all_status:"All Status", name:"Name",
    saving:"Saving...", save_changes:"Save Changes", notes:"Notes",
    notes_placeholder:"Notes...", position:"Position", gender:"Gender",
    nationality:"Nationality", phone:"Phone", send_request:"Send Request",
    page_of:"Page {p} / {total}", showing_range:"Showing {from}–{to} of {total} records",
    /* ── Reports ── */
    reports_title:"Reports", reports_sub:"Full system data report",
    tab_employee:"Employee Report", tab_building:"Building Report",
    select_cols:"Columns", col_code:"Employee Code", col_name:"Full Name",
    col_position:"Position", col_company:"Company", col_status:"Status",
    col_gender:"Gender", col_nationality:"Nationality", col_phone:"Phone",
    col_passport:"Passport No.", col_visa:"Visa No.", deselect_all:"Deselect",
    select_min_col:"Please select at least 1 column", showing:"Showing", of:"of",
    items:"records", total:"Total", active:"Active", resigned:"Resigned",
    on_leave:"On Leave", search_emp:"Search name, code, position...", no_passport:"None",
    /* ── Building ── */
    bld_title:"Building Management", bld_sub:"Managing {n} buildings total",
    bld_office:"Office", bld_dormitory:"Dormitory", bld_floors:"Floors",
    bld_rooms:"Rooms", bld_available:"Available", bld_partial:"Partial", bld_occupied:"Occupied",
    bld_maintenance:"Maintenance", bld_office_bld:"Office Building",
    bld_usage:"Occupancy", bld_people:"People", bld_floor_n:"Floor {n}",
    bld_lobby:"Lobby / Common Area", bld_dorm_rooms:"Dormitory ({n} rooms)",
    bld_avail_rooms:"Available rooms", bld_maint_short:"Maint.", bld_total_rooms:"Total {n} rooms",
    bld_click_change:"Click a room to change its status",
    bld_floor_n_of_bld:"{bld} — Floor {n}",
    bld_office_note:"Office Building · {n} Floors",
    room_n:"Room {n}", room_capacity:"Capacity {cap} · {occ} residents",
    room_full:"Room full ({cap} people)", room_no_occupants:"No residents yet",
    room_residents:"Residents ({n})", room_status:"Status",
    room_add_resident:"Add Resident", room_search:"🔍 Search name / code...",
    room_add_btn:"+ Add to Room", room_not_found:"Employee not found",
    total_buildings:"Total Buildings", total_rooms:"Total Rooms",
    available:"Available", occupied:"Occupied", maintenance:"Maintenance",
    building_name:"Building Name", building_type:"Type", floors:"Floors",
    search_building:"Search building name...", all_types:"All Types", dormitory:"Dormitory",
    occupancy:"Occupancy %", total_occupants:"Tenants", buildings:"buildings",
    /* ── Dashboard ── */
    male:"Male", female:"Female", resigned_total:"Resigned (Total)",
    this_month:"this month", rooms_available:"Available Rooms (Building)",
    rooms_used:"Used {n} rooms",
    /* ── Employees ── */
    employees_title:"Employees", add_employee:"Add Employee",
    employee_code:"Code", employee_name:"Full Name",
    hire_date:"Hire Date", manage:"Manage",
    search_emp_ph:"Search name, code, position...", no_employees:"No employee data found",
    clear_filter:"Clear filter", view:"View",
    found_records:"Found {total} records (showing {from}–{to})",
    confirm_delete_emp:"Delete this employee?",
    confirm_delete_emp_admin:"Send delete request?",
    delete_request_info:"Request will be sent to Super Admin for approval",
    delete_info:"Data will be deleted and cannot be recovered",
    all_genders:"All Genders",
    sort_newest:"Newest", sort_oldest:"Oldest",
    sort_name_az:"Name A-Z", sort_name_za:"Name Z-A",
    view_table:"Table View", view_grid:"Grid View",
    /* ── Companies ── */
    companies_title:"Companies", company_name:"Company Name",
    owner:"Owner", created_by:"Created By", order_no:"No.",
    confirm_delete_co:"Delete this company?",
    delete_permanent:"Data will be permanently deleted and cannot be recovered",
    search_owner:"Search owner...", no_result:"No results found",
    col_in_file:"Name found in file", col_correct:"Correct name",
    id_card_color_staff:"ID Card Color (Staff)",
    id_card_color_manager:"ID Card Color (Manager/Lead)",
    custom_color:"Custom Color", change:"Change",
    /* ── Settings ── */
    settings_title:"Settings", settings_sub:"Manage your account and system configuration",
    tab_account:"Account", tab_password:"Change Password", tab_system:"System",
    account_info:"Account Information", account_sub:"Edit your name and email",
    full_name:"Full Name", name_placeholder:"First and last name",
    current_password:"Current Password", new_password:"New Password",
    confirm_password:"Confirm Password", change_password:"Change Password",
    password_min:"New password must be at least 6 characters",
    system_settings:"System Settings",
    system_sub:"General configuration of the web application",
    sys_name_label:"System Name (shown in Sidebar)",
    admin_email_label:"Admin Email", timezone_label:"Timezone", feature_toggles_title:"Feature Toggles",
    about_settings_title:"About Page", about_settings_sub:"Company/developer info shown on the About page",
    about_company_name_label:"Company Name", about_email_label:"Email",
    about_contact_label:"Contact (name & phone)",
    tab_general:"General", tab_notifications:"Notifications", tab_security:"Security",
    tab_appearance:"Appearance", tab_language:"Language", tab_backup:"Backup & Export",
    feat_audit_logging:"Audit Logging", feat_audit_logging_desc:"Record all user actions in the Audit Log",
    feat_expiry_alerts:"Permit/Visa Expiry Alerts", feat_expiry_alerts_desc:"Notify admins before permits expire",
    feat_expiry_alert_days_label:"Alert before expiry (days)", feat_check_now:"Check Now",
    feat_2fa:"Two-Factor Authentication", feat_2fa_desc:"Require 2FA for Super Admin logins",
    feat_auto_backup:"Automatic Data Backup", feat_auto_backup_desc:"Back up data automatically every day",
    super_admin_only:"Only Super Admin can change this", coming_soon:"Coming soon",
    backup_sleep_note:"Note: backup runs automatically on the first request after the scheduled time — Render's free tier can't run background jobs while the server is asleep",
    backup_run_now:"Backup Now", backup_history_title:"Backup History",
    backup_col_date:"Date", backup_col_size:"Size", backup_col_trigger:"Trigger", backup_download:"Download",
    backup_success:"Backup successful",
    backup_restore:"Restore", backup_restoring:"Restoring...",
    restore_type_confirm:"Type RESTORE to confirm",
    restore_confirm_btn:"Confirm Restore", restore_confirm_mismatch:"Please type RESTORE exactly",
    restore_warning:"⚠️ Restoring will delete all current data and replace it with this backup — the system will save a safety backup of the current state first in case the restore goes wrong",
    restore_success:"Restore successful", restore_failed:"Restore failed",
    appearance_upload_logo:"Upload Logo", appearance_remove_logo:"Remove Logo",
    tfa_status_on:"✅ Enabled", tfa_status_off:"Not enabled yet",
    tfa_enable_btn:"Enable 2FA", tfa_disable_btn:"Disable 2FA", tfa_confirm_disable:"Confirm Disable",
    tfa_disabled_ok:"2FA disabled successfully", tfa_require_label:"Require 2FA (Super Admin)",
    tfa_require_desc:"Require all Super Admins to set up 2FA before accessing the system",
    /* ── Admin/Users ── */
    users_title:"System Users", users_sub:"Manage users and system permissions",
    no_users:"No users", created_at:"Created",
    edit_user:"Edit User", create_user:"Create New User",
    full_name_req:"Full Name *", password_req:"Password *",
    new_password_opt:"New password (blank = no change)",
    select_role:"Select Role",
    companies_assigned:"Companies (assigned)",
    create_company:"Create New Company",
    confirm_delete_user:"Delete this user?",
    delete_user_permanent:"User data will be permanently deleted",
    /* ── AuditLog ── */
    audit_title:"Audit Log", audit_sub:"Full system usage history",
    audit_total:"Total (this page)", audit_user:"User",
    audit_date:"Date / Time", audit_no_match:"No data matching search",
    audit_search_ph:"Search user, company, type...",
    /* ── Import ── */
    import_title:"Import Employees",
    import_sub:"Upload an Excel file to import employees with rooms, documents and permits",
    import_step1:"Step 1: Download Template and fill in data",
    download_template:"Download Excel Template",
    upload_file:"Upload File", drag_drop:"Drag file here or click to select",
    select_company:"Select Company", upload_excel:"Upload Excel File",
    reading_file:"Reading file...",
    step_upload:"Upload File", step_verify:"Verify Format",
    step_review:"Admin Review", step_done:"Complete",
    verify_result:"Format Verification Results",
    reject_reupload:"Reject & Re-upload",
    proceed_review:"Proceed → Admin Review ({n} people)",
    back_review:"Back to Review", new_upload:"New",
    import_success:"✅ Import Successful", imported:"Imported",
    skipped:"Skipped (duplicate/invalid)",
    go_employees:"Go to Employees →",
    waiting_admin:"Waiting for Super Admin Approval",
    send_admin:"📤 Send for Super Admin Approval ({n} people)",
    uploading:"Importing... {n}%", sending:"Sending...",
    people_to_import:"People to import", people_skip:"People to skip (invalid)",
    people_rooms:"People with rooms", people_docs:"People with documents",
    import_to:"Data will be saved to:", import_company:"Company to import:",
    please_select_co:"Please select a Company", no_valid_rows:"No valid rows",
    approve_import:"✅ Approve & Import {n} people",
    upload_new:"Upload New File", import_new:"Import New File",
    /* ── ID Card ── */
    idc_sub:"Manage employee ID Cards — Size 50×85mm",
    idc_select_all:"Select All", idc_print_n:"🖨 Print {n} card(s)", idc_print:"🖨 Print",
    idc_select_multi:"☑ Select Multiple to Print",
    idc_search_ph:"Search name, code, position...",
    idc_total:"Total", idc_has_card:"Has Card", idc_no_card:"No Card", idc_printed:"Printed",
    idc_return_label:"Card Return Status — Resigned Employees",
    idc_has_card_resigned:"Has Card (Resigned)", idc_returned:"Returned", idc_not_returned:"Not Returned",
    idc_selected_n:"☑ Selected {n} item(s)", idc_printable:"printable cards",
    idc_no_data:"No data found", idc_creating:"Creating...", idc_issue:"+ Issue Card",
    idc_card_returned_badge:"Card Returned", idc_saving:"Saving...", idc_receive:"📥 Receive Card",
    idc_print_card:"🖨 Print Card", idc_delete_card:"Delete Card",
    idc_confirm_del:"Delete this ID Card?",
    idc_confirm_del_sub:"The card will be deleted and the employee will have 'No Card'",
    idc_confirm_return_sub:"This will record that the employee has returned their ID Card — this action cannot be undone",
    idc_confirm_return_btn:"📥 Confirm Return",
    idc_prev:"← Prev", idc_next:"Next →",
    idc_page_info:"Page {p} / {total} ({n} records)",
    /* ── Card Requests ── */
    crq_title:"Card Requests", crq_sub:"Manage and review employee ID card requests",
    crq_new_request:"+ New Request",
    crq_search_ph:"Search request no., company, sender...",
    crq_pending:"Pending", crq_approved:"Approved", crq_issued:"Issued", crq_printed:"Printed", crq_completed:"Completed", crq_rejected:"Rejected",
    crq_th_no:"Request No.", crq_th_sender:"Requested By", crq_th_qty:"Quantity", crq_th_date:"Date",
    crq_view:"View Details", crq_download:"Download",
    crq_employee_list:"Employee List", crq_acting:"Processing...",
    crq_download_disabled_tip:"Approve first to download", crq_downloading:"Downloading...",
    crq_start_review:"Start Review", crq_starting_review:"Opening...",
    crq_card_type:"Card Type", crq_requested_at:"Requested At",
    crq_no_match:"No requests matching search",
    /* ── Card Request Detail ── */
    crq_detail_title:"ID Request Detail",
    crq_step_submit:"Submitted", crq_step_review:"Review", crq_step_approve:"Approved",
    crq_step_complete:"Completed", crq_step_print:"Printed", crq_step_reject:"Rejected",
    crq_step_review_approve:"Review & Approve", crq_step_create_print:"Create & Print",
    crq_summary_title:"Request Summary", crq_members:"Members", crq_cards:"Cards",
    crq_purpose:"Purpose", crq_purpose_new_card:"New employee card issuance",
    crq_step_progress:"Step {n}/3 — {label}",
    crq_step_n_of_3:"Step {n}/3",
    crq_pending_banner:"{name} submitted this request — please review the list and info before approving",
    crq_approved_banner:"Approved — ID Cards have been issued to all employees in this request",
    crq_rejected_banner:"This request was rejected",
    crq_back_to_list:"← Back",
    crq_step_n_of_5:"Step {n}/3", crq_heading_pending:"Reviewing",
    crq_heading_review_approve:"Review & Approve Request", crq_heading_create_print:"Create & Print Cards",
    crq_heading_submitted:"Request Submitted", crq_go_to_review:"Start Review →",
    crq_card_summary:"Card Type Summary", crq_print_cards:"Create Cards", crq_approved_ready:"Request approved. You can now create ID cards.",
    crq_heading_issued:"Cards Created — Ready to Print", crq_issued_banner:"Cards created — ready to view and print",
    crq_issued_title:"Created Cards", crq_total:"Total",
    crq_print_settings:"Print Settings", crq_printer_model:"Printer", crq_print_quality:"Print Quality",
    crq_print_name_cb:"Include employee name", crq_quick_preview:"Quick Preview", crq_print_all:"Print All Cards",
    crq_heading_complete:"Fully Completed", crq_complete_sub:"All done — Cards printed and activated",
    crq_printed_info:"{n} card(s) printed · {date} · by {actor}",
    crq_view_id_cards:"View ID Cards", crq_back_list:"Back to List",
    crq_review_warning:"Please review the name list and information before approving",
    crq_admin_note_label:"Admin Notes (optional)", crq_admin_note_ph:"Enter additional notes here...",
    crq_approve_short:"✓ Approve", crq_reject_short:"✕ Reject",
    crq_rollback_to_review:"← Back to Review", crq_rollback_to_approved:"← Back to Approved", crq_rollback_to_issued:"← Back to Issued",
    crq_rollback_confirm_review:"Confirm: Roll back to Review? Status will be reset to pending.", crq_rollback_confirm_approved:"Confirm: Roll back to Approved? Cards issued flag will be reset.", crq_rollback_confirm_issued:"Confirm: Roll back to Issued? Print status will be reset.",
    /* ── AddEmployee ── */
    ae_edit_title:"Edit Employee", ae_edit_sub:"Fill out the details to update the employee.",
    ae_add_sub:"Fill out the details to add a new employee.",
    section_basic_info:"Basic Information", section_additional:"Additional Information",
    section_address:"Address / Profile Info",
    first_name:"First Name", last_name:"Last Name",
    upload_photo:"Upload Photo", auto_generate:"Auto-generate",
    select_gender:"Select Gender", opt_other:"Other",
    select_emp_type:"Select Employee Type",
    opt_fulltime:"Full-time", opt_parttime:"Part-time", opt_contract:"Contract", opt_intern:"Intern",
    opt_inactive:"Inactive",
    province:"Province", district:"District", village:"Village",
    update_employee:"Update Employee", notes_long_ph:"Enter any additional notes here...",
    office_loc_lbl:"🏢 Office Location (Workplace)", dormitory_lbl:"🛏️ Dormitory",
    office_bld_lbl:"Office Building", office_floor_lbl:"Office Floor", office_room_lbl:"Office Room",
    dorm_bld_lbl:"Dormitory Building", floor_lbl:"Floor", room_lbl:"Room",
    sel_office_bld:"-- Select Office Building --", sel_floor_opt:"-- Select Floor --",
    sel_room_opt:"-- Select Room --", not_assigned_opt:"-- Not Assigned --",
    floor_n:"Floor {n}", room_full_tag:"(Full)",
    err_sel_co_first:"Please select a Company first", err_code_fetch:"Failed to fetch code",
    err_firstname:"Please enter First Name", err_lastname:"Please enter Last Name",
    err_sel_company:"Please select a Company", err_email_fmt:"Invalid email format",
    edit_req_sent:"Edit request sent to Super Admin — waiting for approval",
    emp_updated:"Employee updated successfully", emp_added:"Employee added successfully",
    save_failed_msg:"Save failed",
    /* ── Admin/Users ── */
    users_page_title:"User & Roles", col_actions:"Actions",
    add_user_btn:"+ Add User", edit_user_title:"Edit User", add_user_title:"Add User",
    update_btn:"Update", create_user_btn:"Create User",
    new_co_ph:"New Company Name...", cancel_new_co_btn:"✕ Cancel",
    create_new_co_btn:"+ Create New Company", sel_role_opt:"-- Select Role --",
    load_failed:"Failed to load data", fill_required:"Please fill in all required fields",
    please_enter_pw:"Please enter a password",
    user_updated_ok:"User updated successfully", user_created_ok:"User created successfully",
    user_deleted_ok:"User deleted successfully", delete_failed_msg:"Delete failed",
    co_created_ok:"Company created successfully", co_create_fail:"Failed to create Company",
    /* ── BulkPhotoUpload ── */
    bpu_sub:"Upload employee profile photos in bulk",
    bpu_how_to:"How to use:", bpu_name_match:"File name must match the",
    bpu_drag_text:"Drag & drop photos here or click to select",
    bpu_supports:"Supports JPG, PNG, WEBP — max 5MB/photo",
    bpu_selected_n:"Selected {n} photos", bpu_click_change:"Click to change / add photos",
    bpu_uploading:"⏳ Uploading...", bpu_upload_n:"📤 Upload {n} photos",
    bpu_clear:"Clear", bpu_success_n:"✅ Success: {n}", bpu_notfound_n:"❌ Code Not Found: {n}",
    bpu_error_n:"⚠️ Error: {n}", bpu_ok_heading:"✅ Upload Successful",
    bpu_nf_heading:"❌ Employee Code Not Found in System",
    bpu_new_batch:"+ Upload New Batch", bpu_img_only:"Please select image files only",
    bpu_toast_ok:"Upload successful {n}/{total} photos", bpu_toast_err:"An error occurred",
    /* ── Settings ── */
    st_backend_api:"Backend API URL", st_edit_env:"Edit in .env file (VITE_API_URL)",
    save_btn:"Save", st_update_ok:"Data updated successfully", st_update_fail:"Update failed",
    st_pw_ok:"Password changed successfully", st_pw_fail:"Failed to change password",
    st_sys_ok:"System settings saved", st_save_fail:"Save failed",
    st_fill_all:"Please fill in all fields", st_pw_mismatch:"New passwords do not match",
    /* ── EmployeeDetail tabs ── */
    ed_sub:"Manage and organize all employees.",
    tab_basic_info:"Basic Info", tab_profile:"Profile",
    tab_documents:"Documents", tab_permits:"Permits",
    tab_timeline:"Timeline", tab_emp_cards:"Employee Cards",
    /* ── BasicInfoTab ── */
    lbl_date_of_birth:"Date of Birth", lbl_resigned_date:"Resigned Date",
    lbl_resigned_reason:"Resigned Reason", lbl_created_at:"Created At", lbl_updated_at:"Updated At",
    /* ── ProfileTab ── */
    pf_address:"📍 Address", pf_employment:"💼 Employment",
    pf_office_loc:"🏢 Office Location", pf_dormitory:"🛏️ Dormitory",
    pf_notes_sec:"📝 Notes",
    pf_province:"Province (ແຂວງ)", pf_district:"District (ເມືອງ)", pf_village:"Village (ບ້ານ)",
    pf_hire_date:"Hire Date", pf_emp_type:"Employee Type",
    pf_field_col:"Field", pf_value_col:"Value",
    /* ── DocumentsTab ── */
    doc_title:"Documents", doc_add_btn:"+ Add Document",
    doc_type_lbl:"Type", doc_name_lbl:"Document Name *",
    doc_expiry_lbl:"Expiry Date", doc_file_lbl:"File (PDF / Image)",
    doc_file_btn:"Choose File", doc_photo_col:"Photo",
    doc_detail_col:"Name / Details", doc_uploaded_by:"Uploaded By",
    doc_no_data:"No documents yet",
    doc_ph_name:"e.g. Passport No. AB123456", doc_ph_notes:"Additional notes",
    doc_del_preview:"✕ Remove", doc_del_btn:"Delete",
    err_doc_name:"Please enter document name", doc_saved:"Document saved successfully",
    doc_save_fail:"Failed to save", doc_del_confirm:"Delete this document?",
    doc_deleted:"Deleted successfully", doc_del_fail:"Failed to delete",
    /* ── PermitsTab ── */
    permit_title:"Permits / Visa", permit_add_btn:"+ Add Permit",
    permit_type_lbl:"Type *", permit_number_lbl:"Permit Number",
    permit_status_lbl:"Status", permit_issued_lbl:"Issue Date",
    permit_expiry_lbl:"Expiry Date", permit_file_lbl:"Document Photo (Visa / Passport)",
    permit_photo_col:"Photo", permit_no_col:"Permit No.",
    permit_issued_col:"Issue Date", permit_expiry_col:"Expiry Date",
    permit_no_data:"No permits yet",
    permit_ph_number:"e.g. WP-2025-00123", permit_ph_notes:"Notes...",
    permit_del_btn:"Delete", permit_edit_btn:"Edit", permit_edit_save:"Update",
    err_permit_type:"Please enter permit type", permit_edit_ok:"Updated successfully",
    permit_add_ok:"Permit added successfully", permit_save_fail:"Failed to save",
    permit_del_confirm:"Delete this permit?", permit_deleted:"Deleted successfully",
    permit_del_fail:"Failed to delete",
    /* ── TimelineTab ── */
    tl_title:"Change History", tl_add_btn:"+ Record Event",
    tl_event_type:"Event Type", tl_old_value:"Old Value", tl_new_value:"New Value",
    tl_old_ph:"Previous value...", tl_new_ph:"New value...",
    tl_notes_ph:"Additional details...", tl_by:"By:", tl_no_data:"No history yet",
    err_tl_details:"Please enter details", tl_saved:"Recorded successfully",
    tl_save_fail:"Failed to save",
    /* ── ExpiryBadge ── */
    exp_expired:"(Expired)", exp_days_left:"({d} days left)",
    /* ── EmployeeCardDetail ── */
    ecd_title:"Employee Card", ecd_sub:"View employee ID card details and status.",
    ecd_preview_title:"ID Card Preview", ecd_preview_sub:"This is how the ID card will look.",
    ecd_download:"Download", ecd_print:"Print Card",
    ecd_card_info:"Card Information", ecd_no_history:"No history",
    ecd_card_history:"Card History", ecd_card_no:"Card No.",
    ecd_emp_name:"Employee Name", ecd_issued_by:"Issued By",
    ecd_issued_at:"Issued At", ecd_printed_at:"Printed At",
    ecd_returned_at:"Returned At", ecd_returned_by:"Returned By",
    ecd_revoked_at:"Revoked At", ecd_revoked_reason:"Revoked Reason",
    ecd_no_card:"No Card", ecd_hist_dt:"Date / Time",
    ecd_hist_by:"By", ecd_hist_remark:"Remark",
    toast_load_fail:"Failed to load card data", toast_print_ok:"Card printed successfully",
    /* ── ImportApproval ── */
    ia_title:"Import Approval",
    ia_sub:"Review and approve/reject import requests from Company Admin",
    ia_status_pending:"Pending", ia_status_approved:"Approved", ia_status_rejected:"Rejected",
    ia_all:"All", ia_no_batch:"No batches", ia_submitted_by:"Submitted by",
    ia_valid:"Valid", ia_invalid_skip:"Invalid/Skip", ia_total:"Total",
    ia_reject_reason_lbl:"Reject Reason",
    ia_preview_rows:"Preview (first 10 rows)",
    ia_confirm_reject:"Confirm Reject", ia_reject_btn:"✗ Reject",
    ia_processing:"Processing...", ia_select_batch:"Select a batch on the left to review",
    ia_and_more:"... and {n} more rows", ia_reason_ph:"Enter reject reason (optional)...",
    ia_approve_confirm:"Approve importing {n} employees?",
    ia_load_fail:"Failed to load",
    ia_approve_ok:"Approved — imported {n} employees",
    ia_approve_fail:"Approval failed", ia_reject_ok:"Batch rejected",
    ia_reject_fail:"Rejection failed",
    /* ── TapInOut ── */
    tio_title:"Tap In-Out History",
    tio_sub:"Review employee tap in/out scan history by date.",
    tio_stat_ontime:"On Time", tio_stat_late:"Late", tio_stat_working:"Still Working",
    tio_search_ph:"Search employee name or code...",
    tio_col_employee:"Employee", tio_col_date:"Date", tio_col_timein:"Time In",
    tio_col_timeout:"Time Out", tio_col_hours:"Work Hours", tio_col_method:"Scan Method",
    tio_no_data:"No tap in/out records found", tio_no_match:"No records match your filters",
    tio_still_working:"Still Working",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "lo");

  const toggleLang = () => {
    const next = lang === "lo" ? "en" : "lo";
    setLang(next);
    localStorage.setItem("lang", next);
  };

  const t = (key) => translations[lang][key] ?? translations["lo"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
